const arrStocks = [
  {id:'ANDHRAPAP', val: 'Andhra Paper'},
  {id:'ASTRON', val: 'Astron Paper'},
  {id:'BBTCL', val: 'B&B Triplewall'},
  {id:'BALKRISHNA', val: 'Balkrishna Paper'},
  {id:'BALLARPUR', val: 'Ballarpur Inds.'},
  {id:'CENTURYTEX', val: 'Century Textiles'},
  {id:'EMAMIPAP', val: 'Emami Paper'},
  {id:'GENUSPAPER', val: 'Genus Paper & Bo'},
  {id:'JKPAPER', val: 'JK Paper'},
  {id:'KUANTUM', val: 'Kuantum Papers'},
  {id:'MAGNUM', val: 'Magnum Ventures'},
  {id:'MALUPAPER', val: 'Malu Paper'},
  {id:'NRAIL', val: 'N R Agarwal Inds'},
  {id:'ORIENTPPR', val: 'Orient Paper'},
  {id:'PDMJEPAPER', val: 'Pudumjee Paper'},
  {id:'RUCHIRA', val: 'Ruchira Papers'},
  {id:'SATIA', val: 'Satia Industries'},
  {id:'SESHAPAPER', val: 'Seshasayee Paper'},
  {id:'RAMANEWS', val: 'Shree Rama News.'},
  {id:'SHREYANIND', val: 'Shreyans Inds.'},
  {id:'STARPAPER', val: 'Star Paper Mills'},
  {id:'TNPL', val: 'T N Newsprint'},
  {id:'WSTCSTPAPR', val: 'West Coast Paper'},
  {id:'WORTH', val: 'Worth Peripheral'},
  {id:'ATGL', val: 'Adani Total Gas'},
  {id:'DEEPENR', val: 'Deep Energy'},
  {id:'DEEPINDS', val: 'Deep Industries'},
  {id:'GAIL', val: 'GAIL (India)'},
  {id:'GSPL', val: 'Guj.St.Petronet'},
  {id:'IGL', val: 'Indraprastha Gas'},
  {id:'MGL', val: 'Mahanagar Gas'},
  {id:'PETRONET', val: 'Petronet LNG'},
  {id:'3IINFOTECH', val: '3i Infotech'},
  {id:'63MOONS', val: '63 Moons Tech.'},
  {id:'AAATECH', val: 'AAA Technologies'},
  {id:'ACCELYA', val: 'Accelya Solution'},
  {id:'ADROITINFO', val: 'Adroit Info.'},
  {id:'AGCNET', val: 'AGC Networks'},
  {id:'AIRAN', val: 'Airan'},
  {id:'ALANKIT', val: 'Alankit'},
  {id:'ADSL', val: 'Allied Digital'},
  {id:'ALLSEC', val: 'Allsec Tech.'},
  {id:'APOLLO', val: 'Apollo Micro Sys'},
  {id:'AURIONPRO', val: 'Aurionpro Sol.'},
  {id:'AXISCADES', val: 'AXISCADES Tech.'},
  {id:'BARTRONICS', val: 'Bartronics India'},
  {id:'BGLOBAL', val: 'Bharatiya Glob.'},
  {id:'BSOFT', val: 'Birlasoft Ltd'},
  {id:'BLS', val: 'BLS Internat.'},
  {id:'BCG', val: 'Brightcom Group'},
  {id:'CADSYS', val: 'Cadsys (India)'},
  {id:'CALSOFT', val: 'California Soft.'},
  {id:'CTE', val: 'Cambridge Tech.'},
  {id:'CIGNITITEC', val: 'Cigniti Tech.'},
  {id:'COFORGE', val: 'Coforge'},
  {id:'CRANESSOFT', val: 'Cranes Software'},
  {id:'CYBERTECH', val: 'Cybertech Sys.'},
  {id:'CYIENT', val: 'Cyient'},
  {id:'DATAMATICS', val: 'Datamatics Glob.'},
  {id:'DEVIT', val: 'Dev Information'},
  {id:'DUCON', val: 'Ducon Tech'},
  {id:'DSSL', val: 'Dynacons Sys.'},
  {id:'E2E', val: 'E2E Networks'},
  {id:'ECLERX', val: 'eClerx Services'},
  {id:'EXCEL', val: 'Excel Realty'},
  {id:'EXPLEOSOL', val: 'Expleo Solutions'},
  {id:'FCSSOFT', val: 'FCS Software'},
  {id:'FSL', val: 'Firstsour.Solu.'},
  {id:'GENESYS', val: 'Genesys Intl.'},
  {id:'GISOLUTION', val: 'GI Engg.Sol.'},
  {id:'GOLDTECH', val: 'Goldstone Tech.'},
  {id:'GSS', val: 'GSS Infotech'},
  {id:'HAPPSTMNDS', val: 'Happiest Minds'},
  {id:'HCLTECH', val: 'HCL Technologies'},
  {id:'HGS', val: 'Hinduja Global'},
  {id:'HOVS', val: 'HOV Services'},
  {id:'INFIBEAM', val: 'Infibeam Avenues'},
  {id:'INFOBEAN', val: 'InfoBeans Tech.'},
  {id:'INFY', val: 'Infosys'},
  {id:'INNOVANA', val: 'Innovana Think.'},
  {id:'INSPIRISYS', val: 'Inspirisys Sol.'},
  {id:'INTELLECT', val: 'Intellect Design'},
  {id:'INTENTECH', val: 'Intense Tech.'},
  {id:'ISFT', val: 'Intrasoft Tech.'},
  {id:'IZMO', val: 'IZMO'},
  {id:'KELLTONTEC', val: 'Kellton Tech'},
  {id:'KPITTECH', val: 'KPIT Technologi.'},
  {id:'KSOLVES', val: 'Ksolves India'},
  {id:'LTI', val: 'L & T Infotech'},
  {id:'LTTS', val: 'L&T Technology'},
  {id:'LCCINFOTEC', val: 'LCC Infotech'},
  {id:'MAJESCO', val: 'Majesco'},
  {id:'MASTEK', val: 'Mastek'},
  {id:'MEGASOFT', val: 'Megasoft'},
  {id:'MELSTAR', val: 'Melstar Info.'},
  {id:'MINDTECK', val: 'Mindteck (India)'},
  {id:'MINDTREE', val: 'Mindtree'},
  {id:'MPHASIS', val: 'Mphasis'},
  {id:'VISESHINFO', val: 'MPS Infotecnics'},
  {id:'NAZARA', val: 'Nazara Technolo.'},
  {id:'NPST', val: 'Network People'},
  {id:'NEWGEN', val: 'Newgen Software'},
  {id:'NUCLEUS', val: 'Nucleus Soft.'},
  {id:'ONEPOINT', val: 'One Point One'},
  {id:'ONWARDTEC', val: 'Onward Technolog'},
  {id:'OFSS', val: 'Oracle Fin.Serv.'},
  {id:'PALREDTEC', val: 'Palred Technolog'},
  {id:'PERSISTENT', val: 'Persistent Sys'},
  {id:'QUICKHEAL', val: 'Quick Heal Tech'},
  {id:'QUINTEGRA', val: 'Quintegra Soln.'},
  {id:'RSSOFTWARE', val: 'R S Software (I)'},
  {id:'RSYSTEMS', val: 'R Systems Intl.'},
  {id:'RAMCOSYS', val: 'Ramco Systems'},
  {id:'RELIABLE', val: 'Reliable Data'},
  {id:'ROLTA', val: 'Rolta India'},
  {id:'ROUTE', val: 'Route Mobile'},
  {id:'RPSGVENT', val: 'RPSG Ventures'},
  {id:'SAKSOFT', val: 'Saksoft'},
  {id:'SASKEN', val: 'Sasken Technol.'},
  {id:'SECURKLOUD', val: 'SecureKloud Tech'},
  {id:'SIGMA', val: 'Sigma Solve'},
  {id:'SILVERTUC', val: 'Silver Touch'},
  {id:'SOFTTECH', val: 'Softtech Enginee'},
  {id:'SONATSOFTW', val: 'Sonata Software'},
  {id:'SPCENET', val: 'Spacenet Enterpr'},
  {id:'SUBEXLTD', val: 'Subex'},
  {id:'TAKE', val: 'Take Solutions'},
  {id:'TANLA', val: 'Tanla Platforms'},
  {id:'TATAELXSI', val: 'Tata Elxsi'},
  {id:'TCS', val: 'TCS'},
  {id:'TECHM', val: 'Tech Mahindra'},
  {id:'TERASOFT', val: 'Tera Software'},
  {id:'TREJHARA', val: 'Trejhara Solutio'},
  {id:'TRIGYN', val: 'Trigyn Techno.'},
  {id:'VAKRANGEE', val: 'Vakrangee'},
  {id:'WEWIN', val: 'We Win Ltd'},
  {id:'WIPRO', val: 'Wipro'},
  {id:'XCHANGING', val: 'Xchanging Sol.'},
  {id:'XELPMOC', val: 'Xelpmoc Design'},
  {id:'ZENTEC', val: 'Zen Technologies'},
  {id:'ZENSARTECH', val: 'Zensar Tech.'},
  {id:'DPABHUSHAN', val: 'D. P. Abhushan'},
  {id:'GOENKA', val: 'Goenka Diamond'},
  {id:'GOLDIAM', val: 'Goldiam Intl.'},
  {id:'KALYANKJIL', val: 'Kalyan Jewellers'},
  {id:'KANANIIND', val: 'Kanani Industrie'},
  {id:'LGHL', val: 'Laxmi Goldorna'},
  {id:'LYPSAGEMS', val: 'Lypsa Gems'},
  {id:'MOKSH', val: 'Moksh Ornaments'},
  {id:'PCJEWELLER', val: 'PC Jeweller'},
  {id:'PENTAGOLD', val: 'Penta Gold'},
  {id:'RAJESHEXPO', val: 'Rajesh Exports'},
  {id:'RGL', val: 'Renaiss. Global'},
  {id:'SILGO', val: 'Silgo Retail'},
  {id:'SONAHISONA', val: 'Sona Hi Sona'},
  {id:'TBZ', val: 'T B Z'},
  {id:'THANGAMAYL', val: 'Thangamayil Jew.'},
  {id:'TITAN', val: 'Titan Company'},
  {id:'VAIBHAVGBL', val: 'Vaibhav Global'},
  {id:'ZODJRDMKJ', val: 'Zodiac-JRD MKJ'},
  {id:'ASTEC', val: 'Astec Lifescienc'},
  {id:'BAYERCROP', val: 'Bayer Crop Sci.'},
  {id:'BESTAGRO', val: 'Best Agrolife'},
  {id:'BHARATRAS', val: 'Bharat Rasayan'},
  {id:'DHANUKA', val: 'Dhanuka Agritech'},
  {id:'HERANBA', val: 'Heranba Inds'},
  {id:'IPL', val: 'India Pesticides'},
  {id:'INSECTICID', val: 'Insecticid.India'},
  {id:'MOL', val: 'Meghmani Organi.'},
  {id:'NACLIND', val: 'NACL Industries'},
  {id:'PIIND', val: 'P I Industries'},
  {id:'RALLIS', val: 'Rallis India'},
  {id:'SHARDACROP', val: 'Sharda Cropchem'},
  {id:'SIKKO', val: 'Sikko Industries'},
  {id:'SUMICHEM', val: 'Sumitomo Chemi.'},
  {id:'UPL', val: 'UPL'},
  {id:'ANTGRAPHIC', val: 'Antarctica'},
  {id:'DBCORP', val: 'D B Corp'},
  {id:'DNAMEDIA', val: 'Diligent Media'},
  {id:'HTMEDIA', val: 'H T Media'},
  {id:'HMVL', val: 'Hindustan Media'},
  {id:'INFOMEDIA', val: 'Infomedia Press'},
  {id:'JAGRAN', val: 'Jagran Prakashan'},
  {id:'MPSLTD', val: 'MPS'},
  {id:'NAVNETEDUL', val: 'Navneet Educat.'},
  {id:'NDTV', val: 'NDTV'},
  {id:'REPRO', val: 'Repro India'},
  {id:'SCHAND', val: 'S Chand & Compan'},
  {id:'SABEVENTS', val: 'SAB Events'},
  {id:'SAMBHAAV', val: 'Sambhaav Media'},
  {id:'SANDESH', val: 'Sandesh'},
  {id:'SUNDARAM', val: 'Sundaram Multi.'},
  {id:'TVTODAY', val: 'T.V. Today Netw.'},
  {id:'UFO', val: 'UFO Moviez'},
  {id:'ARCOTECH', val: 'Arcotech Ltd'},
  {id:'CENTEXT', val: 'Century Extrus.'},
  {id:'CUBEXTUB', val: 'Cubex Tubings'},
  {id:'HINDALCO', val: 'Hindalco Inds.'},
  {id:'HINDCOPPER', val: 'Hindustan Copper'},
  {id:'HINDZINC', val: 'Hindustan Zinc'},
  {id:'MAANALU', val: 'Maan Aluminium'},
  {id:'MANAKSIA', val: 'Manaksia'},
  {id:'MANAKALUCO', val: 'Manaksia Alumi.'},
  {id:'MMP', val: 'MMP Industries'},
  {id:'NATIONALUM', val: 'Natl. Aluminium'},
  {id:'PRECWIRE', val: 'Prec. Wires (I)'},
  {id:'SAGARDEEP', val: 'Sagardeep Alloys'},
  {id:'TINPLATE', val: 'Tinplate Co.'},
  {id:'APCOTEXIND', val: 'Apcotex Industri'},
  {id:'CCL', val: 'CCL Products'},
  {id:'DTIL', val: 'Dhunseri Tea'},
  {id:'ELGIRUBCO', val: 'Elgi Rubber Co'},
  {id:'GROBTEA', val: 'Grob Tea Co'},
  {id:'GRPLTD', val: 'GRP'},
  {id:'HARRMALAYA', val: 'Harri. Malayalam'},
  {id:'JAYSREETEA', val: 'Jay Shree Tea'},
  {id:'MCLEODRUSS', val: 'Mcleod Russel'},
  {id:'NORBTEAEXP', val: 'Norben Tea'},
  {id:'PKTEA', val: 'Peria Kara. Tea'},
  {id:'ROSSELLIND', val: 'Rossell India'},
  {id:'SEPOWER', val: 'S E Power'},
  {id:'SOMICONVEY', val: 'Somi Conv.Belt.'},
  {id:'TATACOFFEE', val: 'Tata Coffee'},
  {id:'TATACONSUM', val: 'Tata Consumer'},
  {id:'UNITEDTEA', val: 'United Nilgiri'},
  {id:'KOKUYOCMLN', val: 'Kokuyo Camlin'},
  {id:'LINCPEN', val: 'Linc Pen &Plast.'},
  {id:'VASA', val: 'Vasa Retail'},
  {id:'ABB', val: 'A B B'},
  {id:'POWERINDIA', val: 'ABB Power Produc'},
  {id:'AMTL', val: 'Advance Meter.'},
  {id:'APARINDS', val: 'Apar Inds.'},
  {id:'BHEL', val: 'B H E L'},
  {id:'BBL', val: 'Bharat Bijlee'},
  {id:'BRIGHT', val: 'Bright Solar'},
  {id:'CGPOWER', val: 'CG Power & Indu.'},
  {id:'CROMPTON', val: 'Crompton Gr. Con'},
  {id:'EASUNREYRL', val: 'Easun Reyrolle'},
  {id:'EMCO', val: 'EMCO'},
  {id:'FOCUS', val: 'Focus Lighting'},
  {id:'GET&D', val: 'GE T&D India'},
  {id:'GOLDSTAR', val: 'Goldstar Power'},
  {id:'HAVELLS', val: 'Havells India'},
  {id:'HONDAPOWER', val: 'Honda India'},
  {id:'HPL', val: 'HPL Electric'},
  {id:'INDLMETER', val: 'IMP Powers'},
  {id:'INDOTECH', val: 'Indo Tech.Trans.'},
  {id:'INDOSOLAR', val: 'Indosolar'},
  {id:'INOXWIND', val: 'Inox Wind'},
  {id:'JYOTISTRUC', val: 'Jyoti Structures'},
  {id:'KEC', val: 'K E C Intl.'},
  {id:'KALPATPOWR', val: 'Kalpataru Power'},
  {id:'KECL', val: 'Kirl. Electric'},
  {id:'MARINE', val: 'Marine Electric.'},
  {id:'MODISNME', val: 'Modison Metals'},
  {id:'NTL', val: 'Neueon Towers'},
  {id:'REXPIPES', val: 'Rex Pipes&Cables'},
  {id:'S&SPOWER', val: 'S & S Power Swit'},
  {id:'SALZERELEC', val: 'Salzer Electron.'},
  {id:'SCHNEIDER', val: 'Schneider Elect.'},
  {id:'SERVOTECH', val: 'Servotech Power'},
  {id:'SRIRAM', val: 'Shri Ram Switch.'},
  {id:'SIEMENS', val: 'Siemens'},
  {id:'SPECTRUM', val: 'Spectrum Electr.'},
  {id:'SURANASOL', val: 'Surana Solar'},
  {id:'SUZLON', val: 'Suzlon Energy'},
  {id:'SWELECTES', val: 'Swelect Energy'},
  {id:'TRIL', val: 'T R I L'},
  {id:'TARAPUR', val: 'Tarapur Trans'},
  {id:'TDPOWERSYS', val: 'TD Power Systems'},
  {id:'TRITURBINE', val: 'Triveni Turbine'},
  {id:'UJAAS', val: 'Ujaas Energy'},
  {id:'VGUARD', val: 'V-Guard Industri'},
  {id:'VETO', val: 'Veto Switchgears'},
  {id:'VOLTAMP', val: 'Volt.Transform.'},
  {id:'WEBELSOLAR', val: 'Websol Energy'},
  {id:'WFL', val: 'Wonder Fibromats'},
  {id:'BIRLAMONEY', val: 'Adit.Birla Money'},
  {id:'ARIHANTCAP', val: 'Arihant Capital'},
  {id:'DBSTOCKBRO', val: 'DB Intl.Stock'},
  {id:'EMKAY', val: 'Emk.Global Fin.'},
  {id:'GEOJITFSL', val: 'Geojit Fin. Ser.'},
  {id:'INDBANK', val: 'Indbank Merchant'},
  {id:'STEELCITY', val: 'Steel City Sec.'},
  {id:'IFGLEXPOR', val: 'IFGL Refractori.'},
  {id:'RHIM', val: 'RHI Magnesita'},
  {id:'VESUVIUS', val: 'Vesuvius India'},
  {id:'AAREYDRUGS', val: 'Aarey Drugs'},
  {id:'AARTIDRUGS', val: 'Aarti Drugs'},
  {id:'ABBOTINDIA', val: 'Abbott India'},
  {id:'AJANTPHARM', val: 'Ajanta Pharma'},
  {id:'ALBERTDAVD', val: 'Albert David'},
  {id:'ALEMBICLTD', val: 'Alembic'},
  {id:'APLLTD', val: 'Alembic Pharma'},
  {id:'ALKEM', val: 'Alkem Lab'},
  {id:'ALPA', val: 'Alpa Laboratorie'},
  {id:'AMRUTANJAN', val: 'Amrutanjan Healt'},
  {id:'ANURAS', val: 'Anupam Rasayan'},
  {id:'ARVEE', val: 'Arvee Laborat.'},
  {id:'ASTRAZEN', val: 'Astrazeneca Phar'},
  {id:'AUROPHARMA', val: 'Aurobindo Pharma'},
  {id:'BAFNAPH', val: 'Bafna Pharma.'},
  {id:'BALPHARMA', val: 'Bal Pharma'},
  {id:'BETA', val: 'Beta Drugs Ltd'},
  {id:'BIOCON', val: 'Biocon'},
  {id:'BIOFILCHEM', val: 'Biofil Chemicals'},
  {id:'BLISSGVS', val: 'Bliss GVS Pharma'},
  {id:'BROOKS', val: 'Brooks Lab.'},
  {id:'CADILAHC', val: 'Cadila Health.'},
  {id:'CAPLIPOINT', val: 'Caplin Point Lab'},
  {id:'CIPLA', val: 'Cipla'},
  {id:'DCAL', val: 'Dishman Carbogen'},
  {id:'DIVISLAB', val: 'Divi\'s Lab.'},
  {id:'DRREDDY', val: 'Dr Reddy\'s Labs'},
  {id:'ERIS', val: 'ERIS Lifescience'},
  {id:'FDC', val: 'FDC'},
  {id:'GLAND', val: 'Gland Pharma'},
  {id:'GLAXO', val: 'Glaxosmi. Pharma'},
  {id:'GLS', val: 'Glenmark Life'},
  {id:'GLENMARK', val: 'Glenmark Pharma.'},
  {id:'GRANULES', val: 'Granules India'},
  {id:'GUFICBIO', val: 'Gufic BioScience'},
  {id:'HESTERBIO', val: 'Hester Bios'},
  {id:'HIKAL', val: 'Hikal'},
  {id:'INDSWFTLTD', val: 'Ind-Swift'},
  {id:'INDSWFTLAB', val: 'Ind-Swift Labs.'},
  {id:'INDOCO', val: 'Indoco Remedies'},
  {id:'IOLCP', val: 'IOL Chemicals'},
  {id:'IPCALAB', val: 'Ipca Labs.'},
  {id:'JBCHEPHARM', val: 'J B Chem & Pharm'},
  {id:'JAGSNPHARM', val: 'Jagsonpal Pharma'},
  {id:'JUBLPHARMA', val: 'Jubilant Pharmo'},
  {id:'KILITCH', val: 'Kilitch Drugs'},
  {id:'KOPRAN', val: 'Kopran'},
  {id:'KREBSBIO', val: 'Krebs Biochem'},
  {id:'LASA', val: 'Lasa Supergeneri'},
  {id:'LAURUSLABS', val: 'Laurus Labs'},
  {id:'LINCOLN', val: 'Lincoln Pharma.'},
  {id:'LUPIN', val: 'Lupin'},
  {id:'LYKALABS', val: 'Lyka Labs'},
  {id:'MANGALAM', val: 'Mangalam Drugs'},
  {id:'MARKSANS', val: 'Marksans Pharma'},
  {id:'MOREPENLAB', val: 'Morepen Labs.'},
  {id:'NATCOPHARM', val: 'Natco Pharma'},
  {id:'NECLIFE', val: 'Nectar Lifesci.'},
  {id:'NEULANDLAB', val: 'Neuland Labs.'},
  {id:'NOVARTIND', val: 'Novartis India'},
  {id:'ORCHPHARMA', val: 'Orchid Pharma'},
  {id:'ORTINLAB', val: 'Ortin Labs.'},
  {id:'PGHL', val: 'P & G Health Ltd'},
  {id:'PANACEABIO', val: 'Panacea Biotec'},
  {id:'PAR', val: 'Par Drugs & Che.'},
  {id:'PDPL', val: 'Parenteral Drugs'},
  {id:'PFIZER', val: 'Pfizer'},
  {id:'PEL', val: 'Piramal Enterp.'},
  {id:'RPGLIFE', val: 'RPG LifeScience.'},
  {id:'SAKAR', val: 'Sakar Healthcare'},
  {id:'SANOFI', val: 'Sanofi India'},
  {id:'SEQUENT', val: 'Sequent Scien.'},
  {id:'SHILPAMED', val: 'Shilpa Medicare'},
  {id:'SMSLIFE', val: 'SMS Lifesciences'},
  {id:'SMSPHARMA', val: 'SMS Pharma.'},
  {id:'SOLARA', val: 'Solara Active'},
  {id:'STAR', val: 'Strides Pharma'},
  {id:'SUNPHARMA', val: 'Sun Pharma.Inds.'},
  {id:'SUVEN', val: 'Suven Life Scie.'},
  {id:'SUVENPHAR', val: 'Suven Pharma'},
  {id:'SYNGENE', val: 'Syngene Intl.'},
  {id:'THEMISMED', val: 'Themis Medicare'},
  {id:'TORNTPHARM', val: 'Torrent Pharma.'},
  {id:'TTKHLTCARE', val: 'TTK Healthcare'},
  {id:'UNICHEMLAB', val: 'Unichem Labs.'},
  {id:'VENUSREM', val: 'Venus Remedies'},
  {id:'VINEETLAB', val: 'Vineet Laborator'},
  {id:'VIVIMEDLAB', val: 'Vivimed Labs.'},
  {id:'WANBURY', val: 'Wanbury'},
  {id:'WINDLAS', val: 'Windlas Biotech'},
  {id:'WOCKPHARMA', val: 'Wockhardt'},
  {id:'ZOTA', val: 'Zota Health Care'},
  {id:'ESSARSHPNG', val: 'Essar Shipping'},
  {id:'GESHIP', val: 'GE Shipping Co'},
  {id:'GLOBOFFS', val: 'Global Offshore'},
  {id:'MERCATOR', val: 'Mercator'},
  {id:'SCI', val: 'S C I'},
  {id:'SEAMECLTD', val: 'SEAMEC Ltd'},
  {id:'SHREYAS', val: 'Shreyas Shipping'},
  {id:'AUBANK', val: 'AU Small Finance'},
  {id:'AXISBANK', val: 'Axis Bank'},
  {id:'BANDHANBNK', val: 'Bandhan Bank'},
  {id:'BANKBARODA', val: 'Bank of Baroda'},
  {id:'BANKINDIA', val: 'Bank of India'},
  {id:'MAHABANK', val: 'Bank of Maha'},
  {id:'CANBK', val: 'Canara Bank'},
  {id:'CENTRALBK', val: 'Central Bank'},
  {id:'CUB', val: 'City Union Bank'},
  {id:'CSBBANK', val: 'CSB Bank'},
  {id:'DCBBANK', val: 'DCB Bank'},
  {id:'DHANBANK', val: 'Dhanlaxmi Bank'},
  {id:'EQUITASBNK', val: 'Equitas Sma. Fin'},
  {id:'FEDERALBNK', val: 'Federal Bank'},
  {id:'HDFCBANK', val: 'HDFC Bank'},
  {id:'IOB', val: 'I O B'},
  {id:'ICICIBANK', val: 'ICICI Bank'},
  {id:'IDBI', val: 'IDBI Bank'},
  {id:'IDFCFIRSTB', val: 'IDFC First Bank'},
  {id:'INDIANB', val: 'Indian Bank'},
  {id:'INDUSINDBK', val: 'IndusInd Bank'},
  {id:'J&KBANK', val: 'J & K Bank'},
  {id:'KTKBANK', val: 'Karnataka Bank'},
  {id:'KARURVYSYA', val: 'Karur Vysya Bank'},
  {id:'KOTAKBANK', val: 'Kotak Mah. Bank'},
  {id:'PSB', val: 'Pun. & Sind Bank'},
  {id:'PNB', val: 'Punjab Natl.Bank'},
  {id:'RBLBANK', val: 'RBL Bank'},
  {id:'SOUTHBANK', val: 'South Ind.Bank'},
  {id:'SBIN', val: 'St Bk of India'},
  {id:'SURYODAY', val: 'Suryoday Small'},
  {id:'UCOBANK', val: 'UCO Bank'},
  {id:'UJJIVANSFB', val: 'Ujjivan Small'},
  {id:'UNIONBANK', val: 'Union Bank (I)'},
  {id:'YESBANK', val: 'Yes Bank'},
  {id:'20MICRONS', val: '20 Microns'},
  {id:'ASHAPURMIN', val: 'Ashapura Minech.'},
  {id:'BHAGYANGR', val: 'Bhagyanagar Ind'},
  {id:'COALINDIA', val: 'Coal India'},
  {id:'GMDCLTD', val: 'G M D C'},
  {id:'GRAVITA', val: 'Gravita India'},
  {id:'IMPEXFERRO', val: 'Impex Ferro Tech'},
  {id:'IMFA', val: 'Indian Metals'},
  {id:'KIOCL', val: 'KIOCL'},
  {id:'MCL', val: 'Madhav Copper'},
  {id:'MAITHANALL', val: 'Maithan Alloys'},
  {id:'MOIL', val: 'MOIL'},
  {id:'NMDC', val: 'NMDC'},
  {id:'ORISSAMINE', val: 'Orissa Minerals'},
  {id:'ARENTERP', val: 'Rajdarshan Inds'},
  {id:'ROHITFERRO', val: 'Rohit Ferro Tech'},
  {id:'SHIRPUR-G', val: 'Shirpur Gold'},
  {id:'SHYAMCENT', val: 'Shyam Century'},
  {id:'SOUTHWEST', val: 'South West Pinn.'},
  {id:'VEDL', val: 'Vedanta'},
  {id:'GPPL', val: 'Guj Pipavav Port'},
  {id:'APTECHT', val: 'Aptech'},
  {id:'COMPUSOFT', val: 'Compucom Soft.'},
  {id:'EDUCOMP', val: 'Educomp Sol.'},
  {id:'NIITLTD', val: 'NIIT'},
  {id:'UMESLTD', val: 'Usha Mart. Edu.'},
  {id:'ZEELEARN', val: 'Zee Learn'},
  {id:'ACC', val: 'ACC'},
  {id:'AMBUJACEM', val: 'Ambuja Cements'},
  {id:'ANDHRACEMT', val: 'Andhra Cements'},
  {id:'APCL', val: 'Anjani Portland'},
  {id:'BVCL', val: 'Barak Valley'},
  {id:'BIRLACORPN', val: 'Birla Corpn.'},
  {id:'BURNPUR', val: 'Burnpur Cement'},
  {id:'DALBHARAT', val: 'Dalmia BharatLtd'},
  {id:'DECCANCE', val: 'Deccan Cements'},
  {id:'GSCLCEMENT', val: 'Guj. Sidhee Cem.'},
  {id:'HEIDELBERG', val: 'Heidelberg Cem.'},
  {id:'INDIACEM', val: 'India Cements'},
  {id:'JKCEMENT', val: 'J K Cements'},
  {id:'JKLAKSHMI', val: 'JK Lakshmi Cem.'},
  {id:'KCP', val: 'K C P'},
  {id:'KAKATCEM', val: 'Kakatiya Cement'},
  {id:'MANGLMCEM', val: 'Mangalam Cement'},
  {id:'NCLIND', val: 'NCL Industries'},
  {id:'NUVOCO', val: 'Nuvoco Vistas'},
  {id:'ORIENTCEM', val: 'Orient Cement'},
  {id:'PRSMJOHNSN', val: 'Prism Johnson'},
  {id:'SAGCEM', val: 'Sagar Cements'},
  {id:'SANGHIIND', val: 'Sanghi Industrie'},
  {id:'SHREDIGCEM', val: 'Sh. Digvijay Cem'},
  {id:'SHREECEM', val: 'Shree Cement'},
  {id:'STARCEMENT', val: 'Star Cement'},
  {id:'RAMCOCEM', val: 'The Ramco Cement'},
  {id:'ULTRACEMCO', val: 'UltraTech Cem.'},
  {id:'KPIGLOBAL', val: 'K P I Global Inf'},
  {id:'ABAN', val: 'Aban Offshore'},
  {id:'HINDOILEXP', val: 'Hind.Oil Explor.'},
  {id:'ONGC', val: 'O N G C'},
  {id:'OIL', val: 'Oil India'},
  {id:'SELAN', val: 'Selan Expl. Tech'},
  {id:'AARTIIND', val: 'Aarti Industries'},
  {id:'AARTISURF', val: 'Aarti Surfactant'},
  {id:'ADVENZYMES', val: 'Advanced Enzyme'},
  {id:'AKSHARCHEM', val: 'AksharChem (I)'},
  {id:'ALKALI', val: 'Alkali Metals'},
  {id:'ALKYLAMINE', val: 'Alkyl Amines'},
  {id:'AMBANIORG', val: 'Ambani Organics'},
  {id:'ASAHISONG', val: 'Asahi Songwon'},
  {id:'ATUL', val: 'Atul'},
  {id:'BALAMINES', val: 'Balaji Amines'},
  {id:'BASF', val: 'BASF India'},
  {id:'BHAGERIA', val: 'Bhageria Indust.'},
  {id:'BODALCHEM', val: 'Bodal Chemicals'},
  {id:'CAMLINFINE', val: 'Camlin Fine'},
  {id:'CASTROLIND', val: 'Castrol India'},
  {id:'CHEMBOND', val: 'Chembond Chem.'},
  {id:'CHEMCON', val: 'Chemcon Special.'},
  {id:'CHEMFAB', val: 'Chemfab Alka.'},
  {id:'CHEMPLASTS', val: 'Chemplast Sanmar'},
  {id:'CHROMATIC', val: 'Chromatic India'},
  {id:'CLNINDIA', val: 'Clariant Chemica'},
  {id:'CLEAN', val: 'Clean Science'},
  {id:'DEEPAKFERT', val: 'Deepak Fertiliz.'},
  {id:'DEEPAKNTR', val: 'Deepak Nitrite'},
  {id:'DICIND', val: 'DIC India'},
  {id:'DYNPRO', val: 'Dynemic Products'},
  {id:'EXCELINDUS', val: 'Excel Industries'},
  {id:'FAIRCHEMOR', val: 'Fairchem Organic'},
  {id:'FINEORG', val: 'Fine Organic'},
  {id:'FCL', val: 'Fineotex Chem'},
  {id:'FOSECOIND', val: 'Foseco India'},
  {id:'GHCL', val: 'GHCL'},
  {id:'GOACARBON', val: 'Goa Carbon'},
  {id:'GOCLCORP', val: 'GOCL Corpn.'},
  {id:'GODREJIND', val: 'Godrej Industrie'},
  {id:'GULFPETRO', val: 'GP Petroleums'},
  {id:'GRAUWEIL', val: 'Grauer & Weil'},
  {id:'GUJALKALI', val: 'Gujarat Alkalies'},
  {id:'FLUOROCHEM', val: 'Gujarat Fluoroch'},
  {id:'GULFOILLUB', val: 'Gulf Oil Lubric.'},
  {id:'GULPOLY', val: 'Gulshan Polyols'},
  {id:'HSCL', val: 'Himadri Special'},
  {id:'HOCL', val: 'Hind.Organ.Chem.'},
  {id:'HINDCON', val: 'Hindcon Chemical'},
  {id:'IGPL', val: 'I G Petrochems'},
  {id:'INDIAGLYCO', val: 'India Glycols'},
  {id:'IVP', val: 'IVP'},
  {id:'JAYAGROGN', val: 'Jayant Agro Org.'},
  {id:'JOCIL', val: 'Jocil'},
  {id:'JUBLINDS', val: 'Jubilant Inds.'},
  {id:'KANORICHEM', val: 'Kanoria Chem.'},
  {id:'KIRIINDUS', val: 'Kiri Industries'},
  {id:'LXCHEM', val: 'Laxmi Organic'},
  {id:'LINDEINDIA', val: 'Linde India'},
  {id:'MAHICKRA', val: 'Mahickra Chem.'},
  {id:'MFL', val: 'Meghmani Fineche'},
  {id:'NAVINFLUOR', val: 'Navin Fluo.Intl.'},
  {id:'NEOGEN', val: 'Neogen Chemicals'},
  {id:'NOCIL', val: 'NOCIL'},
  {id:'OAL', val: 'Oriental Aromat.'},
  {id:'OCCL', val: 'Oriental Carbon'},
  {id:'PHILIPCARB', val: 'Phillips Carbon'},
  {id:'PIDILITIND', val: 'Pidilite Inds.'},
  {id:'PLASTIBLEN', val: 'Plastiblends (I)'},
  {id:'PODDARMENT', val: 'Poddar Pigments'},
  {id:'PREMEXPLN', val: 'Prem. Explosives'},
  {id:'PRIVISCL', val: 'Privi Speci.'},
  {id:'PROLIFE', val: 'Prolife Indust.'},
  {id:'PUNJABCHEM', val: 'Punjab Chemicals'},
  {id:'REFEX', val: 'Refex Industries'},
  {id:'ROSSARI', val: 'Rossari Biotech'},
  {id:'SHK', val: 'S H Kelkar & Co.'},
  {id:'SANGINITA', val: 'Sanginita Chemi.'},
  {id:'SEYAIND', val: 'Seya Industries'},
  {id:'SHREEPUSHK', val: 'Sh.Pushkar Chem.'},
  {id:'SOLARINDS', val: 'Solar Industries'},
  {id:'SRHHYPOLTD', val: 'Sr.Rayala.Hypo'},
  {id:'SUDARSCHEM', val: 'Sudarshan Chem.'},
  {id:'TNPETRO', val: 'T N Petro Prod.'},
  {id:'TATACHEM', val: 'Tata Chemicals'},
  {id:'TATVA', val: 'Tatva Chintan'},
  {id:'TIRUMALCHM', val: 'Thirumalai Chem.'},
  {id:'TIDEWATER', val: 'Tide Water Oil'},
  {id:'UCL', val: 'Ushanti Colour'},
  {id:'VSCL', val: 'Vadivarhe Speci.'},
  {id:'VALIANTORG', val: 'Valiant Organics'},
  {id:'VIDHIING', val: 'Vidhi Specialty'},
  {id:'VIKASWSP', val: 'Vikas Wsp'},
  {id:'VINATIORGA', val: 'Vinati Organics'},
  {id:'VISHNU', val: 'Vishnu Chemicals'},
  {id:'A2ZINFRA', val: 'A2Z Infra Engg.'},
  {id:'AARON', val: 'Aaron Industries'},
  {id:'ACE', val: 'Action Const.Eq.'},
  {id:'ADORWELD', val: 'Ador Welding'},
  {id:'BEML', val: 'BEML Ltd'},
  {id:'BDL', val: 'Bharat Dynamics'},
  {id:'CARBORUNIV', val: 'Carborundum Uni.'},
  {id:'CEBBCO', val: 'Commercial Eng.'},
  {id:'CUMMINSIND', val: 'Cummins India'},
  {id:'DENORA', val: 'DE Nora India'},
  {id:'DYNAMATECH', val: 'Dynamatic Tech.'},
  {id:'EIMCOELECO', val: 'Eimco Elecon(I)'},
  {id:'ELECON', val: 'Elecon Engg.Co'},
  {id:'ELGIEQUIP', val: 'Elgi Equipments'},
  {id:'ESABINDIA', val: 'Esab India'},
  {id:'FELIX', val: 'Felix Industries'},
  {id:'GMMPFAUDLR', val: 'GMM Pfaudler'},
  {id:'GRAPHITE', val: 'Graphite India'},
  {id:'GREAVESCOT', val: 'Greaves Cotton'},
  {id:'GRINDWELL', val: 'Grindwell Norton'},
  {id:'GUJAPOLLO', val: 'Guj Apollo Inds'},
  {id:'HEG', val: 'HEG'},
  {id:'HERCULES', val: 'Hercules Hoists'},
  {id:'HAL', val: 'Hind.Aeronautics'},
  {id:'HLEGLAS', val: 'HLE Glascoat'},
  {id:'INGERRAND', val: 'Ingersoll-Rand'},
  {id:'ISGEC', val: 'ISGEC Heavy'},
  {id:'JASH', val: 'Jash Engineering'},
  {id:'KABRAEXTRU', val: 'Kabra Extrusion'},
  {id:'KENNAMET', val: 'Kennametal India'},
  {id:'KIRLOSBROS', val: 'Kirl. Brothers'},
  {id:'KIRLOSENG', val: 'Kirloskar Oil'},
  {id:'KSB', val: 'KSB'},
  {id:'LATTEYS', val: 'Latteys Industri'},
  {id:'LOKESHMACH', val: 'Lokesh Mach.'},
  {id:'MANUGRAPH', val: 'Manugraph India'},
  {id:'MAZDA', val: 'Mazda'},
  {id:'NITINFIRE', val: 'Nitin Fire Prot.'},
  {id:'ORIENTABRA', val: 'Orient Abrasives'},
  {id:'PITTIENG', val: 'Pitti Engg.'},
  {id:'POWERMECH', val: 'Power Mech Proj.'},
  {id:'PRAJIND', val: 'Praj Industries'},
  {id:'PREMIER', val: 'Premier'},
  {id:'REVATHI', val: 'Revathi Equipmnt'},
  {id:'SANGHVIMOV', val: 'Sanghvi Movers'},
  {id:'SHAKTIPUMP', val: 'Shakti Pumps'},
  {id:'SWARAJENG', val: 'Swaraj Engines'},
  {id:'TEXRAIL', val: 'Texmaco Rail'},
  {id:'THERMAX', val: 'Thermax'},
  {id:'TIL', val: 'TIL'},
  {id:'TWL', val: 'Titagarh Wagons'},
  {id:'TRF', val: 'TRF'},
  {id:'UNIDT', val: 'United Drilling'},
  {id:'WABAG', val: 'Va Tech Wabag'},
  {id:'WALCHANNAG', val: 'Walchan. Inds.'},
  {id:'WENDT', val: 'Wendt India'},
  {id:'WINDMACHIN', val: 'Windsor Machines'},
  {id:'YUKEN', val: 'Yuken India'},
  {id:'COCHINSHIP', val: 'Cochin Shipyard'},
  {id:'GRSE', val: 'Garden Reach Sh.'},
  {id:'MAZDOCK', val: 'Mazagon Dock'},
  {id:'RNAVAL', val: 'Reliance Nav.Eng'},
  {id:'ASAHIINDIA', val: 'Asahi India Glas'},
  {id:'BANARBEADS', val: 'Banaras Beads'},
  {id:'BOROLTD', val: 'Borosil'},
  {id:'BORORENEW', val: 'Borosil Renew.'},
  {id:'HINDNATGLS', val: 'Hind.Natl.Glass'},
  {id:'JIKIND', val: 'JIK Industries'},
  {id:'LAOPALA', val: 'La Opala RG'},
  {id:'GODFRYPHLP', val: 'Godfrey Phillips'},
  {id:'GOLDENTOBC', val: 'Golden Tobacco'},
  {id:'ITC', val: 'ITC'},
  {id:'VSTIND', val: 'VST Industries'},
  {id:'BIGBLOC', val: 'BIGBLOC Const.'},
  {id:'EVERESTIND', val: 'Everest Inds.'},
  {id:'HIL', val: 'Hil Ltd'},
  {id:'RAMCOIND', val: 'Ramco Inds.'},
  {id:'VISAKAIND', val: 'Visaka Industrie'},
  {id:'INDIGRID', val: 'India Grid Trust'},
  {id:'PGINVIT', val: 'Powergrid Infra.'},
  {id:'CEREBRAINT', val: 'Cerebra Integr.'},
  {id:'COMPINFO', val: 'Compuage Info.'},
  {id:'DLINKINDIA', val: 'D-Link India'},
  {id:'HCL-INSYS', val: 'HCL Infosystems'},
  {id:'MRO-TEK', val: 'MRO-TEK Realty'},
  {id:'PANACHE', val: 'Panache Digilife'},
  {id:'TVSELECT', val: 'TVS Elec.'},
  {id:'ASHOKLEY', val: 'Ashok Leyland'},
  {id:'ATULAUTO', val: 'Atul Auto'},
  {id:'BAJAJ-AUTO', val: 'Bajaj Auto'},
  {id:'EICHERMOT', val: 'Eicher Motors'},
  {id:'ESCORTS', val: 'Escorts'},
  {id:'FORCEMOT', val: 'Force Motors'},
  {id:'HEROMOTOCO', val: 'Hero Motocorp'},
  {id:'HINDMOTORS', val: 'Hindustan Motors'},
  {id:'M&M', val: 'M & M'},
  {id:'MARUTI', val: 'Maruti Suzuki'},
  {id:'SMLISUZU', val: 'SML ISUZU'},
  {id:'TATAMOTORS', val: 'Tata Motors'},
  {id:'TATAMTRDVR', val: 'Tata Motors-DVR'},
  {id:'TVSMOTOR', val: 'TVS Motor Co.'},
  {id:'VSTTILLERS', val: 'VST Till. Tract.'},
  {id:'INDIAMART', val: 'Indiamart Inter.'},
  {id:'NAUKRI', val: 'Info Edg.(India)'},
  {id:'JUSTDIAL', val: 'Just Dial'},
  {id:'NURECA', val: 'Nureca'},
  {id:'ZOMATO', val: 'Zomato Ltd'},
  {id:'ADANIGREEN', val: 'Adani Green'},
  {id:'ADANIPOWER', val: 'Adani Power'},
  {id:'ADANITRANS', val: 'Adani Transmissi'},
  {id:'BFUTILITIE', val: 'BF Utilities'},
  {id:'CESC', val: 'CESC'},
  {id:'ENERGYDEV', val: 'Energy Devl.Co.'},
  {id:'GIPCL', val: 'Guj Inds. Power'},
  {id:'DPSCLTD', val: 'India Power Corp'},
  {id:'INDOWIND', val: 'Indowind Energy'},
  {id:'IWEL', val: 'Inox Wind Energy'},
  {id:'JPPOWER', val: 'JP Power Ven.'},
  {id:'JSWENERGY', val: 'JSW Energy'},
  {id:'KARMAENG', val: 'Karma Energy Ltd'},
  {id:'KKVAPOW', val: 'KKV Agro Powers'},
  {id:'NHPC', val: 'NHPC Ltd'},
  {id:'NLCINDIA', val: 'NLC India'},
  {id:'NTPC', val: 'NTPC'},
  {id:'GREENPOWER', val: 'Orient Green'},
  {id:'POWERGRID', val: 'Power Grid Corpn'},
  {id:'RTNINDIA', val: 'RattanIndia Ent'},
  {id:'RTNPOWER', val: 'Rattanindia Pow.'},
  {id:'RPOWER', val: 'Reliance Power'},
  {id:'SJVN', val: 'SJVN'},
  {id:'SOLEX', val: 'Solex Energy'},
  {id:'TATAPOWER', val: 'Tata Power Co.'},
  {id:'TORNTPOWER', val: 'Torrent Power'},
  {id:'BIRET', val: 'Brookfield India'},
  {id:'EMBASSY', val: 'Embassy Off.REIT'},
  {id:'MINDSPACE', val: 'Mindspace Busine'},
  {id:'3MINDIA', val: '3M India'},
  {id:'ADANIENT', val: 'Adani Enterp.'},
  {id:'AEGISCHEM', val: 'Aegis Logistics'},
  {id:'AKG', val: 'AKG Exim'},
  {id:'AMBICAAGAR', val: 'Ambica Agarbat.'},
  {id:'ANIKINDS', val: 'Anik Industries'},
  {id:'ANMOL', val: 'Anmol India'},
  {id:'ASPINWALL', val: 'Aspinwall & Co'},
  {id:'BALAXI', val: 'Balaxi Pharma'},
  {id:'BCONCEPTS', val: 'Brand Concepts'},
  {id:'CARTRADE', val: 'Cartrade Tech'},
  {id:'CREATIVE', val: 'Creative Newtech'},
  {id:'DCI', val: 'DC Infotech'},
  {id:'FCONSUMER', val: 'Future Consumer'},
  {id:'HEXATRADEX', val: 'Hexa Tradex'},
  {id:'KHAITANLTD', val: 'Khaitan (India)'},
  {id:'KOTHARIPRO', val: 'Kothari Products'},
  {id:'KRIDHANINF', val: 'Kridhan Infra'},
  {id:'MMTC', val: 'MMTC'},
  {id:'MSTCLTD', val: 'MSTC'},
  {id:'OPTIEMUS', val: 'Optiemus Infra.'},
  {id:'PRAXIS', val: 'Praxis Home'},
  {id:'PROINDIA', val: 'Proseed India'},
  {id:'PTC', val: 'PTC India'},
  {id:'RMCL', val: 'Radha Madh.Corp.'},
  {id:'RAIN', val: 'Rain Industries'},
  {id:'RAJMET', val: 'Rajnandini Metal'},
  {id:'REDINGTON', val: 'Redington India'},
  {id:'STCINDIA', val: 'S T C'},
  {id:'SAKUMA', val: 'Sakuma Exports'},
  {id:'SHANKARA', val: 'Shankara Build.'},
  {id:'SHIVAUM', val: 'Shiv Aum Steels'},
  {id:'SHRENIK', val: 'Shrenik'},
  {id:'SHUBHLAXMI', val: 'Shubhlaxmi Jewel'},
  {id:'SICAGEN', val: 'Sicagen India'},
  {id:'SIDDHIKA', val: 'Siddhika Coatins'},
  {id:'SIGIND', val: 'Signet Industrie'},
  {id:'SIRCA', val: 'Sirca Paints'},
  {id:'SHIL', val: 'Somany Home Inn.'},
  {id:'SIL', val: 'Standard Inds.'},
  {id:'STEELXIND', val: 'Steel Exchange'},
  {id:'SUULD', val: 'Suumaya Indust.'},
  {id:'SVPGLOB', val: 'SVP Global'},
  {id:'TEMBO', val: 'Tembo Global'},
  {id:'UNIENTER', val: 'Uniphos Enter.'},
  {id:'URJA', val: 'Urja Global'},
  {id:'VAISHALI', val: 'Vaishali Pharma'},
  {id:'VCL', val: 'Vaxtex Cotfab'},
  {id:'VIKASLIFE', val: 'Vikas Lifecare'},
  {id:'VINYLINDIA', val: 'Vinyl Chemicals'},
  {id:'VIVIDHA', val: 'Visagar Polytex'},
  {id:'YAARII', val: 'Yaarii Digital'},
  {id:'21STCENMGM', val: '21st Cent. Mgmt.'},
  {id:'3PLAND', val: '3P Land Hold.'},
  {id:'5PAISA', val: '5Paisa Capital'},
  {id:'AAVAS', val: 'AAVAS Financiers'},
  {id:'ABCAPITAL', val: 'Aditya Birla Cap'},
  {id:'ALMONDZ', val: 'Almondz Global'},
  {id:'ANGELBRKG', val: 'Angel Broking'},
  {id:'APTUS', val: 'Aptus Value Hou.'},
  {id:'ARMANFIN', val: 'Arman Financial'},
  {id:'ASCOM', val: 'Ascom Leasing &'},
  {id:'AUSOMENT', val: 'Ausom Enter.'},
  {id:'BAJFINANCE', val: 'Bajaj Finance'},
  {id:'BAJAJFINSV', val: 'Bajaj Finserv'},
  {id:'BAJAJHLDNG', val: 'Bajaj Holdings'},
  {id:'BFINVEST', val: 'BF Investment'},
  {id:'BLBLIMITED', val: 'BLB'},
  {id:'BLUECHIP', val: 'Blue Chip India'},
  {id:'CANFINHOME', val: 'Can Fin Homes'},
  {id:'CAPTRUST', val: 'Capital Trust'},
  {id:'CGCL', val: 'Capri Global'},
  {id:'CENTRUM', val: 'Centrum Capital'},
  {id:'CHOLAHLDNG', val: 'Chola Financial'},
  {id:'CHOLAFIN', val: 'Cholaman.Inv.&Fn'},
  {id:'CONSOFINVT', val: 'Cons. Finvest'},
  {id:'CORALFINAC', val: 'Coral India Fin.'},
  {id:'CREDITACC', val: 'CreditAcc. Gram.'},
  {id:'CREST', val: 'Crest Ventures'},
  {id:'DCMFINSERV', val: 'DCM Financial'},
  {id:'DELPHIFX', val: 'Delphi World'},
  {id:'DHANI', val: 'Dhani Services'},
  {id:'DHUNINV', val: 'Dhunseri Invest.'},
  {id:'DOLAT', val: 'Dolat Investment'},
  {id:'EDELWEISS', val: 'Edelweiss.Fin.'},
  {id:'EQUITAS', val: 'Equitas Holdings'},
  {id:'GANGESSECU', val: 'Ganges Securitie'},
  {id:'GFLLIMITED', val: 'GFL'},
  {id:'GICHSGFIN', val: 'GIC Housing Fin'},
  {id:'GLFL', val: 'Guj. Lease Fin.'},
  {id:'GUJSTATFIN', val: 'Guj. State Fin.'},
  {id:'HDFC', val: 'H D F C'},
  {id:'HUDCO', val: 'H U D C O'},
  {id:'HBSL', val: 'HB Stockholdings'},
  {id:'HDFCAMC', val: 'HDFC AMC'},
  {id:'HOMEFIRST', val: 'Home First Finan'},
  {id:'IDFC', val: 'I D F C'},
  {id:'IRFC', val: 'I R F C'},
  {id:'ICDSLTD', val: 'ICDS'},
  {id:'ISEC', val: 'ICICI Securities'},
  {id:'IFCI', val: 'IFCI'},
  {id:'IIFL', val: 'IIFL Finance'},
  {id:'IIFLSEC', val: 'IIFL Securities'},
  {id:'IIFLWAM', val: 'IIFL Wealth Mgt'},
  {id:'IVC', val: 'IL&FS Inv.Manag.'},
  {id:'IBULHSGFIN', val: 'Indiabulls Hous.'},
  {id:'IITL', val: 'Indl. Inv. Trust'},
  {id:'INDOTHAI', val: 'Indo Thai Sec.'},
  {id:'INDOSTAR', val: 'Indostar Capital'},
  {id:'INVENTURE', val: 'Inventure Grow.'},
  {id:'JPOLYINVST', val: 'Jindal Poly Inve'},
  {id:'JMFINANCIL', val: 'JM Financial'},
  {id:'JSWHL', val: 'JSW Holdings'},
  {id:'KICL', val: 'Kalyani Invest.'},
  {id:'KEYFINSERV', val: 'Keynote Finan.'},
  {id:'KHANDSE', val: 'Khandwala Sec.'},
  {id:'KIRLOSIND', val: 'Kirloskar Indus.'},
  {id:'L&TFH', val: 'L&T Fin.Holdings'},
  {id:'LFIC', val: 'Lak. Fin. & Indl'},
  {id:'LICHSGFIN', val: 'LIC Housing Fin.'},
  {id:'M&MFIN', val: 'M & M Fin. Serv.'},
  {id:'MAHSCOOTER', val: 'Mah. Scooters'},
  {id:'MAHAPEXLTD', val: 'Maha Rashtra Apx'},
  {id:'MANAPPURAM', val: 'Manappuram Fin.'},
  {id:'MASFIN', val: 'MAS FINANC SER'},
  {id:'MASKINVEST', val: 'MASK INVESTMENTS'},
  {id:'MFSL', val: 'Max Financial'},
  {id:'MAXVIL', val: 'Max Ventures'},
  {id:'MCDHOLDING', val: 'McDowell Hold.'},
  {id:'MOTILALOFS', val: 'Motil.Oswal.Fin.'},
  {id:'MOTOGENFIN', val: 'Motor & Gen Fin'},
  {id:'MUTHOOTCAP', val: 'Muthoot Cap.Serv'},
  {id:'MUTHOOTFIN', val: 'Muthoot Finance'},
  {id:'NDGL', val: 'Naga Dhunseri'},
  {id:'NAGREEKCAP', val: 'Nagreeka Cap.'},
  {id:'NAHARCAP', val: 'Nahar Capital'},
  {id:'NSIL', val: 'Nalwa Sons Invst'},
  {id:'NBIFIN', val: 'NBI Indl. Fin.'},
  {id:'NAM-INDIA', val: 'Nippon Life Ind.'},
  {id:'ONELIFECAP', val: 'Onelife Capital'},
  {id:'BINDALAGRO', val: 'Oswal Green Tech'},
  {id:'PAISALO', val: 'Paisalo Digital'},
  {id:'PALASHSECU', val: 'Palash Securi.'},
  {id:'SRGINFOTEC', val: 'Pan India Corpor'},
  {id:'PILANIINVS', val: 'Pilani Invest.'},
  {id:'PNBGILTS', val: 'PNB Gilts'},
  {id:'PNBHOUSING', val: 'PNB Housing'},
  {id:'POONAWALLA', val: 'Poonawalla Fin'},
  {id:'PFC', val: 'Power Fin.Corpn.'},
  {id:'PRIMESECU', val: 'Prime Securities'},
  {id:'PFS', val: 'PTC India Fin'},
  {id:'RANEHOLDIN', val: 'Rane Holdings'},
  {id:'RECLTD', val: 'REC Ltd'},
  {id:'RELCAPITAL', val: 'Reliance Capital'},
  {id:'RHFL', val: 'Reliance Home'},
  {id:'RELIGARE', val: 'Religare Enterp.'},
  {id:'REPCOHOME', val: 'Repco Home Fin'},
  {id:'SASTASUNDR', val: 'Sastasundar Ven.'},
  {id:'SATIN', val: 'Satin Creditcare'},
  {id:'SBICARD', val: 'SBI Cards'},
  {id:'SHAREINDIA', val: 'Share India Sec.'},
  {id:'SHRIRAMCIT', val: 'Shri.City Union.'},
  {id:'SRTRANSFIN', val: 'Shriram Trans.'},
  {id:'SILINV', val: 'SIL Investments'},
  {id:'SMARTLINK', val: 'Smartlink Hold.'},
  {id:'SMCGLOBAL', val: 'SMC Global Sec.'},
  {id:'SPANDANA', val: 'Spandana Sphoort'},
  {id:'SREINFRA', val: 'SREI Infra. Fin.'},
  {id:'SCAPDVR', val: 'Stampade Cap-DVR'},
  {id:'STAMPEDE', val: 'Stampede Cap.'},
  {id:'STEL', val: 'STEL Holdings'},
  {id:'SUMMITSEC', val: 'Summit Securitie'},
  {id:'SUNDARMHLD', val: 'Sundaram Fin.Hol'},
  {id:'SUNDARMFIN', val: 'Sundaram Finance'},
  {id:'TATAINVEST', val: 'Tata Inv.Corpn.'},
  {id:'TCIFINANCE', val: 'TCI Finance'},
  {id:'THEINVEST', val: 'The Invest.Trust'},
  {id:'TIMESGTY', val: 'Times Guaranty'},
  {id:'TFCILTD', val: 'Tour. Fin. Corp.'},
  {id:'TFL', val: 'Transwar.Fin.'},
  {id:'UGROCAP', val: 'Ugro Capital'},
  {id:'UJJIVAN', val: 'Ujjivan Fin.Ser.'},
  {id:'UTIAMC', val: 'UTI AMC'},
  {id:'VHL', val: 'Vardhman Hold.'},
  {id:'VIJIFIN', val: 'Viji Finance'},
  {id:'VLSFINANCE', val: 'VLS Finance'},
  {id:'WEALTH', val: 'Wealth First Por'},
  {id:'WELINV', val: 'Welspun Investme'},
  {id:'WILLAMAGOR', val: 'Williamson Magor'},
  {id:'AARVI', val: 'Aarvi Encon'},
  {id:'AILIMITED', val: 'Abhishek Integr.'},
  {id:'ACEINTEG', val: 'Ace Integrated'},
  {id:'AFFLE', val: 'Affle India'},
  {id:'AGRITECH', val: 'Agri-Tech India'},
  {id:'AIROLAM', val: 'Airo Lam'},
  {id:'AJOONI', val: 'Ajooni Biotech'},
  {id:'AWHCL', val: 'Antony Waste han'},
  {id:'APEX', val: 'Apex Frozen Food'},
  {id:'ADL', val: 'Archidply Decor'},
  {id:'ARCHIDPLY', val: 'Archidply Inds.'},
  {id:'AROGRANITE', val: 'Aro Granite Inds'},
  {id:'AVANTIFEED', val: 'Avanti Feeds'},
  {id:'BANKA', val: 'Banka Bioloo'},
  {id:'BSHSL', val: 'Bombay Super Hyb'},
  {id:'BSE', val: 'BSE'},
  {id:'CDSL', val: 'C D S L'},
  {id:'CAMS', val: 'Cams Services'},
  {id:'CENTURYPLY', val: 'Century Plyboard'},
  {id:'CONFIPET', val: 'Confidence Petro'},
  {id:'CONTI', val: 'Continental Seed'},
  {id:'COX&KINGS', val: 'Cox & Kings'},
  {id:'CROWN', val: 'Crown Lifters'},
  {id:'CUPID', val: 'Cupid'},
  {id:'DRCSYSTEMS', val: 'DRC Systems'},
  {id:'DREDGECORP', val: 'Dredging Corpn.'},
  {id:'EASEMYTRIP', val: 'Easy Trip Plann.'},
  {id:'FMNL', val: 'Future Market'},
  {id:'GKWLIMITED', val: 'GKW'},
  {id:'GODREJAGRO', val: 'Godrej Agrovet'},
  {id:'GREENLAM', val: 'Greenlam Industr'},
  {id:'GREENPANEL', val: 'Greenpanel Inds.'},
  {id:'GREENPLY', val: 'Greenply Industr'},
  {id:'GUJGASLTD', val: 'Gujarat Gas'},
  {id:'IEX', val: 'Indian Energy Ex'},
  {id:'JINDALPHOT', val: 'Jindal Photo'},
  {id:'JIYAECO', val: 'Jiya Eco-Product'},
  {id:'JUBLINGREA', val: 'Jubilant Ingrevia'},
  {id:'KAPSTON', val: 'Kapston Facilit.'},
  {id:'KSCL', val: 'Kaveri Seed Co.'},
  {id:'KEERTI', val: 'Keerti Knowledge'},
  {id:'KTIL', val: 'Kesar Terminals'},
  {id:'MADHAV', val: 'Madhav Marbles'},
  {id:'MANGTIMBER', val: 'Mangalam Timber'},
  {id:'MATRIMONY', val: 'Matrimony.com'},
  {id:'MAXIND', val: 'Max India Ltd'},
  {id:'MILTON', val: 'Milton Industri.'},
  {id:'MITCON', val: 'Mitcon Consult.'},
  {id:'MODIRUBBER', val: 'Modi Rubber'},
  {id:'MCX', val: 'Multi Comm. Exc.'},
  {id:'NATHBIOGEN', val: 'Nath Bio-Genes'},
  {id:'NAVKARCORP', val: 'Navkar Corporat.'},
  {id:'NESCO', val: 'NESCO'},
  {id:'NETWORK18', val: 'Netwrk.18 Media'},
  {id:'OMFURN', val: 'Onfurn India'},
  {id:'ORIENTALTL', val: 'Oriental Trimex'},
  {id:'PARTYCRUS', val: 'Party Cruisers'},
  {id:'PAVNAIND', val: 'Pavna Industries'},
  {id:'POKARNA', val: 'Pokarna'},
  {id:'PRESSMN', val: 'Pressman Adv.'},
  {id:'PTL', val: 'PTL Enterprises'},
  {id:'RUCHINFRA', val: 'Ruchi Infrastr.'},
  {id:'RUSHIL', val: 'Rushil Decor'},
  {id:'SECURCRED', val: 'SecUR Credential'},
  {id:'OSWALSEEDS', val: 'Shreeoswal Seeds'},
  {id:'SIS', val: 'SIS'},
  {id:'SORILINFRA', val: 'SORIL Infra'},
  {id:'SPARC', val: 'SPARC'},
  {id:'HAVISHA', val: 'Sri Havisha'},
  {id:'STYLAMIND', val: 'Stylam Industrie'},
  {id:'SUVIDHAA', val: 'Suvidhaa Info.'},
  {id:'TCIEXP', val: 'TCI Express'},
  {id:'TEAMLEASE', val: 'Team Lease Serv.'},
  {id:'THOMASCOOK', val: 'Thomas Cook (I)'},
  {id:'TOTAL', val: 'Total Transport'},
  {id:'TIINDIA', val: 'Tube Investments'},
  {id:'UNIVPHOTO', val: 'Universus Photo'},
  {id:'VENKEYS', val: 'Venky\'s (India)'},
  {id:'VERTOZ', val: 'Vertoz Advertis.'},
  {id:'VIKASPROP', val: 'Vikas Proppant'},
  {id:'VIMTALABS', val: 'Vimta Labs'},
  {id:'WIPL', val: 'W I Plywoods'},
  {id:'WATERBASE', val: 'Waterbase'},
  {id:'BAGFILMS', val: 'BAG Films'},
  {id:'BALAJITELE', val: 'Balaji Telefilms'},
  {id:'BTML', val: 'Bodhi Tree'},
  {id:'CINELINE', val: 'Cineline India'},
  {id:'CINEVISTA', val: 'Cinevista'},
  {id:'CREATIVEYE', val: 'Creative Eye'},
  {id:'DELTACORP', val: 'Delta Corp'},
  {id:'DEN', val: 'Den Networks'},
  {id:'DGCONTENT', val: 'Digicontent'},
  {id:'DISHTV', val: 'Dish TV India'},
  {id:'DQE', val: 'DQ Entertain.'},
  {id:'DALALSTCOM', val: 'DSJ Keep Learn'},
  {id:'ENIL', val: 'Ent.Network'},
  {id:'EROSMEDIA', val: 'Eros Intl.Media'},
  {id:'GTPL', val: 'GTPL Hathway'},
  {id:'HATHWAY', val: 'Hathway Cable'},
  {id:'IMAGICAA', val: 'Imagica. Enter.'},
  {id:'INOXLEISUR', val: 'Inox Leisure'},
  {id:'JAINSTUDIO', val: 'Jain Studios'},
  {id:'JUMPNET', val: 'Jump Networks'},
  {id:'MPTODAY', val: 'Madhya Prad. Tod'},
  {id:'MUKTAARTS', val: 'Mukta Arts'},
  {id:'RADIOCITY', val: 'Music Broadcast'},
  {id:'NEXTMEDIA', val: 'Next Mediaworks'},
  {id:'NXTDIGITAL', val: 'NxtDigital'},
  {id:'ORTEL', val: 'Ortel Commu.'},
  {id:'PFOCUS', val: 'Prime Focus'},
  {id:'PNC', val: 'Prit Nandy Comm.'},
  {id:'PVR', val: 'PVR'},
  {id:'RADAAN', val: 'Radaan Media.'},
  {id:'RAJTV', val: 'Raj Television'},
  {id:'SAREGAMA', val: 'Saregama India'},
  {id:'SHEMAROO', val: 'Shemaroo Entert.'},
  {id:'SILLYMONKS', val: 'Silly Monks'},
  {id:'SITINET', val: 'Siti Networks'},
  {id:'SABTN', val: 'Sri Adhik. Bros.'},
  {id:'SUNTV', val: 'Sun TV Network'},
  {id:'TIPSINDLTD', val: 'Tips Industries'},
  {id:'TOUCHWOOD', val: 'Touchwood Enter.'},
  {id:'TVVISION', val: 'TV Vision'},
  {id:'TV18BRDCST', val: 'TV18 Broadcast'},
  {id:'WONDERLA', val: 'Wonderla Holiday'},
  {id:'ZEEL', val: 'Zee Entertainmen'},
  {id:'ZEEMEDIA', val: 'Zee Media'},
  {id:'BPCL', val: 'B P C L'},
  {id:'CHENNPETRO', val: 'C P C L'},
  {id:'HINDPETRO', val: 'H P C L'},
  {id:'IOC', val: 'I O C L'},
  {id:'MRPL', val: 'M R P L'},
  {id:'RELIANCE', val: 'Reliance Industr'},
  {id:'AIAENG', val: 'AIA Engineering'},
  {id:'BHARATFORG', val: 'Bharat Forge'},
  {id:'DCM', val: 'DCM'},
  {id:'ELECTCAST', val: 'Electrost.Cast.'},
  {id:'GANGAFORGE', val: 'Ganga Forging'},
  {id:'HILTON', val: 'Hilton Met.Forg.'},
  {id:'JAYNECOIND', val: 'Jayaswal Neco'},
  {id:'KALYANIFRG', val: 'Kalyani Forge'},
  {id:'LAKPRE', val: 'Lak. Prec. Screw'},
  {id:'LGBFORGE', val: 'LGB Forge'},
  {id:'MMFL', val: 'M M Forgings'},
  {id:'MAHINDCIE', val: 'Mahindra CIE'},
  {id:'METALFORGE', val: 'Metalyst Forg.'},
  {id:'NELCAST', val: 'Nelcast'},
  {id:'RKFORGE', val: 'Ramkrishna Forg.'},
  {id:'SONACOMS', val: 'Sona BLW Precis.'},
  {id:'STERTOOLS', val: 'Sterling Tools'},
  {id:'SUNDRMFAST', val: 'Sundram Fasten.'},
  {id:'SGIL', val: 'Synergy Green'},
  {id:'TIRUPATIFL', val: 'Tirupati Forge'},
  {id:'ALCHEM', val: 'Alchemist'},
  {id:'ANDHRSUGAR', val: 'Andhra Sugars'},
  {id:'ANDREWYU', val: 'Andrew Yule & Co'},
  {id:'BALMLAWRIE', val: 'Balmer Lawrie'},
  {id:'BBTC', val: 'Bombay Burmah'},
  {id:'DCMSHRIRAM', val: 'DCM Shriram'},
  {id:'GILLANDERS', val: 'Gillanders Arbut'},
  {id:'KESORAMIND', val: 'Kesoram Inds.'},
  {id:'NBVENTURES', val: 'Nava Bharat Vent'},
  {id:'QUESS', val: 'Quess Corp'},
  {id:'SURANAT&P', val: 'Surana Telecom'},
  {id:'EVEREADY', val: 'Eveready Inds.'},
  {id:'HBLPOWER', val: 'HBL Power System'},
  {id:'NIPPOBATRY', val: 'Indo National'},
  {id:'AKSHOPTFBR', val: 'Aksh Optifibre'},
  {id:'BCP', val: 'B.C. Power'},
  {id:'BIRLACABLE', val: 'Birla Cable'},
  {id:'CMICABLES', val: 'CMI'},
  {id:'CORDSCABLE', val: 'Cords Cable'},
  {id:'DIAPOWER', val: 'Diamond Power'},
  {id:'FINCABLES', val: 'Finolex Cables'},
  {id:'GEEKAYWIRE', val: 'Geekay Wires'},
  {id:'GODHA', val: 'Godha Cabcon'},
  {id:'KEI', val: 'KEI Industries'},
  {id:'PARACABLES', val: 'Paramount Comm.'},
  {id:'POLYCAB', val: 'Polycab India'},
  {id:'STLTECH', val: 'Sterlite Tech.'},
  {id:'TNTELE', val: 'T N Telecom.'},
  {id:'UNIVCABLES', val: 'Universal Cables'},
  {id:'VMARCIND', val: 'V-Marc India'},
  {id:'VINDHYATEL', val: 'Vindhya Telelink'},
  {id:'APOLLOPIPE', val: 'Apollo Pipes'},
  {id:'ARROWGREEN', val: 'Arrow Greentech'},
  {id:'ASTRAL', val: 'Astral'},
  {id:'AVROIND', val: 'Avro India'},
  {id:'AVSL', val: 'AVSL Industries'},
  {id:'BEARDSELL', val: 'Beardsell'},
  {id:'FINPIPE', val: 'Finolex Inds.'},
  {id:'JAICORPLTD', val: 'Jai Corp'},
  {id:'JISLDVREQS', val: 'Jain Irrigat-DVR'},
  {id:'JISLJALEQS', val: 'Jain Irrigation'},
  {id:'KINGFA', val: 'Kingfa Science'},
  {id:'KSHITIJPOL', val: 'Kshitij Polyline'},
  {id:'MAHEPC', val: 'Mahindra EPC'},
  {id:'MAYURUNIQ', val: 'Mayur Uniquoters'},
  {id:'MOLDTKPAC', val: 'Mold-Tek Pack.'},
  {id:'NILKAMAL', val: 'Nilkamal Ltd'},
  {id:'PEARLPOLY', val: 'Pearl Polymers'},
  {id:'PILITA', val: 'Pil Italica Life'},
  {id:'PPL', val: 'Prakash Pipes'},
  {id:'PREMIERPOL', val: 'Premier Polyfilm'},
  {id:'PRINCEPIPE', val: 'Prince Pipes'},
  {id:'RMDRIP', val: 'R M Drip & Sprin'},
  {id:'RESPONIND', val: 'Responsive Ind'},
  {id:'SAFARI', val: 'Safari Inds.'},
  {id:'SANCO', val: 'Sanco Industries'},
  {id:'SPTL', val: 'Sintex Plastics'},
  {id:'SMVD', val: 'SMVD Poly Pack'},
  {id:'SUPREMEIND', val: 'Supreme Inds.'},
  {id:'TAINWALCHM', val: 'Tainwala Chem.'},
  {id:'TEXMOPIPES', val: 'Texmo Pipes'},
  {id:'TIJARIA', val: 'Tijaria Polypipe'},
  {id:'TIMETECHNO', val: 'Time Technoplast'},
  {id:'TOKYOPLAST', val: 'Tokyo Plast Intl'},
  {id:'VIPIND', val: 'V I P Inds.'},
  {id:'VIKASECO', val: 'Vikas Ecotech'},
  {id:'XPROINDIA', val: 'XPRO India'},
  {id:'AGARIND', val: 'Agarwal Indl.'},
  {id:'BEPL', val: 'Bhansali Engg.'},
  {id:'DCW', val: 'DCW'},
  {id:'DVL', val: 'Dhunseri Vent.'},
  {id:'INEOSSTYRO', val: 'INEOS Styrolut.'},
  {id:'KOTHARIPET', val: 'Kothari Petroche'},
  {id:'MANALIPETC', val: 'Manali Petrochem'},
  {id:'PANAMAPET', val: 'Panama Petrochem'},
  {id:'SOTL', val: 'Savita Oil Tech'},
  {id:'SUPPETRO', val: 'Supreme Petroch.'},
  {id:'ABINFRA', val: 'A B Infrabuild'},
  {id:'AKASH', val: 'Akash InfraProj.'},
  {id:'ARSSINFRA', val: 'ARSS Infra'},
  {id:'ARTNIRMAN', val: 'Art Nirman Ltd'},
  {id:'BLKASHYAP', val: 'B.L.Kashyap'},
  {id:'BRNL', val: 'Bharat Road'},
  {id:'BSELINFRA', val: 'BSEL Infra.'},
  {id:'CANDC', val: 'C & C Constrn.'},
  {id:'CCCL', val: 'C C C L'},
  {id:'CMMIPL', val: 'CMM Infraproj'},
  {id:'DRL', val: 'Dhanuka Realty'},
  {id:'GANESHHOUC', val: 'Ganesh Housing'},
  {id:'GAYAHWS', val: 'Gayatri Highways'},
  {id:'GAYAPROJ', val: 'Gayatri Projects'},
  {id:'GENCON', val: 'Generic Engineer'},
  {id:'GIRIRAJ', val: 'Giriraj Civil'},
  {id:'GPTINFRA', val: 'GPT Infraproject'},
  {id:'HGINFRA', val: 'H.G. Infra Engg.'},
  {id:'HCC', val: 'Hind.Construct.'},
  {id:'INDIANHUME', val: 'Indian Hume Pipe'},
  {id:'SUBCAPCITY', val: 'Intl Construct'},
  {id:'ITDCEM', val: 'ITD Cem'},
  {id:'JMCPROJECT', val: 'JMC Projects'},
  {id:'JPASSOCIAT', val: 'JP Associates'},
  {id:'KNRCON', val: 'KNR Construct.'},
  {id:'LODHA', val: 'Macrotech Devel.'},
  {id:'MADHUCON', val: 'Madhucon Project'},
  {id:'MAHLIFE', val: 'Mahindra Life.'},
  {id:'MANINFRA', val: 'Man Infra'},
  {id:'MANAV', val: 'Manav Infra'},
  {id:'MBLINFRA', val: 'MBL Infrast'},
  {id:'NCC', val: 'NCC'},
  {id:'NILAINFRA', val: 'Nila Infrastruct'},
  {id:'NILASPACES', val: 'Nila Spaces'},
  {id:'NIRAJ', val: 'Niraj Cement'},
  {id:'PBAINFRA', val: 'P B A Infra.'},
  {id:'PARSVNATH', val: 'Parsvnath Devl.'},
  {id:'PATELENG', val: 'Patel Engineerin'},
  {id:'PNCINFRA', val: 'PNC Infratech'},
  {id:'PSPPROJECT', val: 'PSP Projects'},
  {id:'PUNJLLOYD', val: 'Punj Lloyd'},
  {id:'RVNL', val: 'Rail Vikas'},
  {id:'RAMKY', val: 'Ramky Infra'},
  {id:'RKEC', val: 'RKEC Projects'},
  {id:'RPPINFRA', val: 'RPP Infra Proj.'},
  {id:'REPL', val: 'Rudrabhish. Ent.'},
  {id:'SSINFRA', val: 'S.S. Infra. Dev.'},
  {id:'SADBHAV', val: 'Sadbhav Engg.'},
  {id:'SADBHIN', val: 'Sadbhav Infra.'},
  {id:'SETUINFRA', val: 'Setubandhan Inf.'},
  {id:'SIMPLEXINF', val: 'Simplex Infra'},
  {id:'SKIL', val: 'SKIL Infrastr'},
  {id:'UNIVASTU', val: 'Univastu India'},
  {id:'VASCONEQ', val: 'Vascon Engineers'},
  {id:'WELENT', val: 'Welspun Enterp'},
  {id:'ADFFOODS', val: 'ADF Foods'},
  {id:'BAJAJCON', val: 'Bajaj Consumer'},
  {id:'BRITANNIA', val: 'Britannia Inds.'},
  {id:'CLSEL', val: 'Chamanlal Setia'},
  {id:'COLPAL', val: 'Colgate-Palmoliv'},
  {id:'DABUR', val: 'Dabur India'},
  {id:'DANGEE', val: 'Dangee Dums'},
  {id:'DFMFOODS', val: 'DFM Foods'},
  {id:'DODLA', val: 'Dodla Dairy'},
  {id:'EMAMILTD', val: 'Emami'},
  {id:'EIFFL', val: 'Euro India Fresh'},
  {id:'GALAXYSURF', val: 'Galaxy Surfact.'},
  {id:'GILLETTE', val: 'Gillette India'},
  {id:'GODREJCP', val: 'Godrej Consumer'},
  {id:'HATSUN', val: 'Hatsun Agro'},
  {id:'HERITGFOOD', val: 'Heritage Foods'},
  {id:'HINDUNILVR', val: 'Hind. Unilever'},
  {id:'HNDFDS', val: 'Hindustan Foods'},
  {id:'JHS', val: 'JHS Sven.Lab.'},
  {id:'JYOTHYLAB', val: 'Jyothy Labs'},
  {id:'KAYA', val: 'Kaya Ltd'},
  {id:'KRBL', val: 'KRBL'},
  {id:'DAAWAT', val: 'L T Foods'},
  {id:'MARICO', val: 'Marico'},
  {id:'BECTORFOOD', val: 'Mrs Bectors'},
  {id:'NGIL', val: 'Nakoda Group'},
  {id:'NARMADA', val: 'Narmada Agrobase'},
  {id:'NESTLEIND', val: 'Nestle India'},
  {id:'PGHH', val: 'P & G Hygiene'},
  {id:'PARAGMILK', val: 'Parag Milk Foods'},
  {id:'DIAMONDYD', val: 'Prataap Snacks'},
  {id:'SANWARIA', val: 'Sanwaria Consum.'},
  {id:'SARVESHWAR', val: 'Sarveshwar Foods'},
  {id:'SKMEGGPROD', val: 'SKM Egg Prod.'},
  {id:'TASTYBITE', val: 'Tasty Bite Eat.'},
  {id:'UMANGDAIRY', val: 'Umang Dairies'},
  {id:'VADILALIND', val: 'Vadilal Inds.'},
  {id:'VBL', val: 'Varun Beverages'},
  {id:'WALPAR', val: 'Walpar Nutrition'},
  {id:'ZYDUSWELL', val: 'Zydus Wellness'},
  {id:'ACCURACY', val: 'Accuracy Shippi.'},
  {id:'ALLCARGO', val: 'Allcargo Logist.'},
  {id:'ARSHIYA', val: 'Arshiya'},
  {id:'AVG', val: 'AVG Logistics'},
  {id:'BLUEDART', val: 'Blue Dart Expres'},
  {id:'CONCOR', val: 'Container Corpn.'},
  {id:'DRSDILIP', val: 'DRS Dilip Road'},
  {id:'FSC', val: 'Future Supply'},
  {id:'GDL', val: 'Gateway Distr.'},
  {id:'GATI', val: 'Gati'},
  {id:'JALAN', val: 'Jalan Transol.'},
  {id:'JITFINFRA', val: 'JITF Infra Logis'},
  {id:'MAHESHWARI', val: 'Maheshwari Logi.'},
  {id:'MAHLOG', val: 'Mahindra Logis.'},
  {id:'NECCLTD', val: 'North Eastn.Car.'},
  {id:'PATINTLOG', val: 'Patel Integrated'},
  {id:'SVLL', val: 'Shree Vasu Logis'},
  {id:'SICAL', val: 'Sical Logistics'},
  {id:'SNOWMAN', val: 'Snowman Logistic'},
  {id:'TARACHAND', val: 'Tara Chand'},
  {id:'TCI', val: 'Transport Corp.'},
  {id:'VRLLOG', val: 'VRL Logistics'},
  {id:'BURGERKING', val: 'Burger King'},
  {id:'COFFEEDAY', val: 'Coffee Day Enter'},
  {id:'DEVYANI', val: 'Devyani Intl.'},
  {id:'JUBLFOOD', val: 'Jubilant Food.'},
  {id:'WESTLIFE', val: 'Westlife Develop'},
  {id:'AKZOINDIA', val: 'Akzo Nobel'},
  {id:'ASIANPAINT', val: 'Asian Paints'},
  {id:'BERGEPAINT', val: 'Berger Paints'},
  {id:'INDIGOPNTS', val: 'Indigo Paints'},
  {id:'KANSAINER', val: 'Kansai Nerolac'},
  {id:'SHALPAINTS', val: 'Shalimar Paints'},
  {id:'AMDIND', val: 'AMD Industries'},
  {id:'BKMINDST', val: 'BKM Industries'},
  {id:'CONTROLPR', val: 'Control Print'},
  {id:'COSMOFILMS', val: 'Cosmo Films'},
  {id:'EMMBI', val: 'Emmbi Industries'},
  {id:'EPL', val: 'EPL Ltd'},
  {id:'ESTER', val: 'Ester Industries'},
  {id:'EKC', val: 'Everest Kanto'},
  {id:'FLEXITUFF', val: 'Flexituff Vent.'},
  {id:'GUJRAFFIA', val: 'Guj. Raffia Inds'},
  {id:'HITECHCORP', val: 'Hitech Corp.'},
  {id:'HUHTAMAKI', val: 'Huhtamaki India'},
  {id:'JINDALPOLY', val: 'Jindal Poly Film'},
  {id:'KANPRPLA', val: 'Kanpur Plastipa.'},
  {id:'NAHARPOLY', val: 'Nahar Poly'},
  {id:'ORICONENT', val: 'Oricon Enterpris'},
  {id:'ORIENTLTD', val: 'Orient Press'},
  {id:'POLYPLEX', val: 'Polyplex Corpn'},
  {id:'RPPL', val: 'Rajshree Polypac'},
  {id:'ROLLT', val: 'Rollatainers'},
  {id:'SHREERAMA', val: 'Sh. Rama Multi.'},
  {id:'TCPLPACK', val: 'TCPL Packaging'},
  {id:'TPLPLASTEH', val: 'TPL Plastech'},
  {id:'UFLEX', val: 'Uflex'},
  {id:'AAKASH', val: 'Aakash Explor.'},
  {id:'ALPHAGEO', val: 'Alphageo (India)'},
  {id:'JINDRILL', val: 'Jindal Drilling'},
  {id:'AGROPHOS', val: 'Agro Phos India'},
  {id:'ARIES', val: 'Aries Agro'},
  {id:'BOHRA', val: 'Bohra Industries'},
  {id:'CHAMBLFERT', val: 'Chambal Fert.'},
  {id:'COROMANDEL', val: 'Coromandel Inter'},
  {id:'FACT', val: 'F A C T'},
  {id:'GNFC', val: 'G N F C'},
  {id:'GSFC', val: 'G S F C'},
  {id:'KHAICHEM', val: 'Khaitan Chemical'},
  {id:'KRISHANA', val: 'Krishana Phosch.'},
  {id:'MBAPL', val: 'M B Agro Prod.'},
  {id:'MADRASFERT', val: 'Madras Fertilize'},
  {id:'MANGCHEFER', val: 'Mangalore Chem.'},
  {id:'NAGAFERT', val: 'Nagarjuna Fert.'},
  {id:'NFL', val: 'Natl.Fertilizer'},
  {id:'RCF', val: 'R C F'},
  {id:'SPIC', val: 'S P I C'},
  {id:'ZUARI', val: 'Zuari Agro Chem.'},
  {id:'HSIL', val: 'HSIL'},
  {id:'GOKEX', val: 'Gokaldas Exports'},
  {id:'KPRMILL', val: 'K P R Mill Ltd'},
  {id:'KKCL', val: 'Kewal Kir.Cloth.'},
  {id:'KITEX', val: 'Kitex Garments'},
  {id:'PAGEIND', val: 'Page Industries'},
  {id:'PGIL', val: 'Pearl Global Ind'},
  {id:'RUPA', val: 'Rupa & Co'},
  {id:'ZODIACLOTH', val: 'Zodiac Cloth. Co'},
  {id:'CAREERP', val: 'Career Point'},
  {id:'CLEDUCATE', val: 'CL Educate'},
  {id:'GLOBAL', val: 'Global Education'},
  {id:'MTEDUCARE', val: 'MT Educare'},
  {id:'TREEHOUSE', val: 'Tree House Edu.'},
  {id:'CARERATING', val: 'CARE Ratings'},
  {id:'CRISIL', val: 'CRISIL'},
  {id:'ICRA', val: 'ICRA'},
  {id:'APOLLOTYRE', val: 'Apollo Tyres'},
  {id:'BALKRISIND', val: 'Balkrishna Inds'},
  {id:'BIRLATYRE', val: 'Birla Tyres'},
  {id:'CEATLTD', val: 'CEAT'},
  {id:'GOODYEAR', val: 'Goodyear India'},
  {id:'INNOVATIVE', val: 'Innovative Tyres'},
  {id:'JKTYRE', val: 'JK Tyre & Indust'},
  {id:'MRF', val: 'MRF'},
  {id:'TVSSRICHAK', val: 'TVS Srichakra'},
  {id:'NIBL', val: 'NRB Indl Bearing'},
  {id:'SCHAEFFLER', val: 'Schaeffler India'},
  {id:'SKFINDIA', val: 'SKF India'},
  {id:'DIGISPICE', val: 'DigiSpice Tech.'},
  {id:'BATAINDIA', val: 'Bata India'},
  {id:'BIL', val: 'Bhartiya Intl.'},
  {id:'KHADIM', val: 'Khadim India'},
  {id:'LIBERTSHOE', val: 'Liberty Shoes'},
  {id:'MIRZAINT', val: 'Mirza Internatio'},
  {id:'RELAXO', val: 'Relaxo Footwear'},
  {id:'SREEL', val: 'Sreeleathers'},
  {id:'SUPERHOUSE', val: 'Superhouse Ltd'},
  {id:'AARVEEDEN', val: 'Aarvee Denims'},
  {id:'AICHAMP', val: 'AI Champ.Inds.'},
  {id:'ALOKINDS', val: 'Alok Industries'},
  {id:'ALPSINDUS', val: 'Alps Industries'},
  {id:'AMBIKCO', val: 'Ambika Cotton'},
  {id:'ARVIND', val: 'Arvind Ltd'},
  {id:'ASHIMASYN', val: 'Ashima'},
  {id:'AYMSYNTEX', val: 'AYM Syntex'},
  {id:'BANG', val: 'Bang Overseas'},
  {id:'BASML', val: 'Bannari Amm Spg.'},
  {id:'BANSWRAS', val: 'Banswara Syntex'},
  {id:'BHANDARI', val: 'Bhandari Hosiery'},
  {id:'BOMDYEING', val: 'Bombay Dyeing'},
  {id:'BRFL', val: 'Bombay Rayon'},
  {id:'BSL', val: 'BSL'},
  {id:'CANTABIL', val: 'Cantabil Retail'},
  {id:'CELEBRITY', val: 'Celebrity Fash.'},
  {id:'CENTENKA', val: 'Century Enka'},
  {id:'CNOVAPETRO', val: 'CIL Nova Petro.'},
  {id:'DAMODARIND', val: 'Damodar Indust.'},
  {id:'DCMNVL', val: 'DCM Nouvelle'},
  {id:'DOLLAR', val: 'Dollar Industrie'},
  {id:'DONEAR', val: 'Donear Inds.'},
  {id:'ELAND', val: 'E-Land Apparel'},
  {id:'EASTSILK', val: 'ESI'},
  {id:'EUROTEXIND', val: 'Eurotex Industri'},
  {id:'FILATEX', val: 'Filatex India'},
  {id:'GANECOS', val: 'Ganesha Ecosphe.'},
  {id:'GANGOTRI', val: 'Gangotri Textile'},
  {id:'GARFIBRES', val: 'Garware Tech.'},
  {id:'GINNIFILA', val: 'Ginni Filaments'},
  {id:'GLOBE', val: 'Globe Textiles'},
  {id:'GRASIM', val: 'Grasim Inds'},
  {id:'GRETEX', val: 'Gretex Industrie'},
  {id:'GTNIND', val: 'GTN Industries'},
  {id:'GTNTEX', val: 'GTN Textiles'},
  {id:'HIMATSEIDE', val: 'Himatsing. Seide'},
  {id:'INDIANCARD', val: 'Indian CardCloth'},
  {id:'INDTERRAIN', val: 'Indian Terrain'},
  {id:'ICIL', val: 'Indo Count Inds.'},
  {id:'INDORAMA', val: 'Indo Rama Synth.'},
  {id:'INTEGRA', val: 'Integra Garments'},
  {id:'IRISDOREME', val: 'Iris Clothings'},
  {id:'JAKHARIA', val: 'Jakharia Fabric'},
  {id:'JBFIND', val: 'JBF Industries'},
  {id:'JETKNIT', val: 'Jet Knitwears'},
  {id:'JINDCOT', val: 'Jindal Cotex Ltd'},
  {id:'JINDWORLD', val: 'Jindal Worldwide'},
  {id:'LAGNAM', val: 'Lagnam Spintex'},
  {id:'LAXMIMACH', val: 'Lak. Mach. Works'},
  {id:'LAMBODHARA', val: 'Lambodhara Text.'},
  {id:'LAXMICOT', val: 'Laxmi Cotspin'},
  {id:'LIBAS', val: 'Libas Consumer'},
  {id:'LOVABLE', val: 'Lovable Lingerie'},
  {id:'LUXIND', val: 'Lux Industries'},
  {id:'MARALOVER', val: 'Maral Overseas'},
  {id:'MDL', val: 'Marvel Decor'},
  {id:'MITTAL', val: 'Mittal Life Styl'},
  {id:'MHHL', val: 'Mohini Health'},
  {id:'MOHITIND', val: 'Mohit Industries'},
  {id:'MOHOTAIND', val: 'Mohota Indust.'},
  {id:'MONTECARLO', val: 'Monte Carlo Fas.'},
  {id:'MORARJEE', val: 'Morarjee Text.'},
  {id:'NAGREEKEXP', val: 'Nagreeka Exports'},
  {id:'NAHARINDUS', val: 'Nahar Indl. Ent.'},
  {id:'NAHARSPING', val: 'Nahar Spinning'},
  {id:'NDL', val: 'Nandan Denim'},
  {id:'JAIPURKURT', val: 'Nandani Creation'},
  {id:'NITINSPIN', val: 'Nitin Spinners'},
  {id:'ORBTEXP', val: 'Orbit Exports'},
  {id:'PASHUPATI', val: 'Pashupati Cotsp.'},
  {id:'PATSPINLTD', val: 'Patspin India'},
  {id:'PDSMFL', val: 'PDS Multi.'},
  {id:'PIONEEREMB', val: 'Pion. Embroider.'},
  {id:'PRADIP', val: 'Pradip Overseas'},
  {id:'PRECOT', val: 'Precot'},
  {id:'PRITI', val: 'Priti Internati.'},
  {id:'RAJRAYON', val: 'Raj Rayon Inds.'},
  {id:'RAJVIR', val: 'Rajvir Inds.'},
  {id:'RAMGOPOLY', val: 'Ramgopal Polytex'},
  {id:'RAYMOND', val: 'Raymond'},
  {id:'RSWM', val: 'RSWM Ltd'},
  {id:'RUBYMILLS', val: 'Ruby Mills'},
  {id:'SPAL', val: 'S P Apparels'},
  {id:'SALONA', val: 'Salona Cotspin'},
  {id:'SANGAMIND', val: 'Sangam India'},
  {id:'SARLAPOLY', val: 'Sarla Performanc'},
  {id:'SFL', val: 'Sheela Foam'},
  {id:'SPYL', val: 'Shekhawati Poly.'},
  {id:'SHIVAMILLS', val: 'Shiva Mills'},
  {id:'SHIVATEX', val: 'Shiva Texyarn'},
  {id:'SINTEX', val: 'Sintex Inds.'},
  {id:'SIYSIL', val: 'Siyaram Silk'},
  {id:'SKSTEXTILE', val: 'SKS Textiles'},
  {id:'SOMATEX', val: 'Soma Textiles'},
  {id:'SPENTEX', val: 'Spentex Inds.'},
  {id:'SPLIL', val: 'SPL Industries'},
  {id:'SRF', val: 'SRF'},
  {id:'SGL', val: 'STL Global'},
  {id:'SUMEETINDS', val: 'Sumeet Industrie'},
  {id:'SUPERSPIN', val: 'Super Spinning'},
  {id:'SURYALAXMI', val: 'Suryalak. Cott.'},
  {id:'SUTLEJTEX', val: 'Sutlej Textiles'},
  {id:'SWANENERGY', val: 'Swan Energy'},
  {id:'TTL', val: 'T T'},
  {id:'TCNSBRANDS', val: 'TCNS Clothing Co'},
  {id:'THOMASCOTT', val: 'Thomas Scott'},
  {id:'TRIDENT', val: 'Trident'},
  {id:'UNITEDPOLY', val: 'United Polyfab'},
  {id:'VARDHACRLC', val: 'Vardhman Acrylic'},
  {id:'VARDMNPOLY', val: 'Vardhman Polytex'},
  {id:'VTL', val: 'Vardhman Textile'},
  {id:'VIPCLOTHNG', val: 'VIP Clothing'},
  {id:'VISHAL', val: 'Vishal Fabrics'},
  {id:'WEIZMANIND', val: 'Weizmann'},
  {id:'WELSPUNIND', val: 'Welspun India'},
  {id:'ZENITHEXPO', val: 'Zenith Exports'},
  {id:'ASIANTILES', val: 'Asian Granito'},
  {id:'CERA', val: 'Cera Sanitary.'},
  {id:'EXXARO', val: 'Exxaro Tiles'},
  {id:'KAJARIACER', val: 'Kajaria Ceramics'},
  {id:'LEXUS', val: 'Lexus Granito'},
  {id:'MURUDCERA', val: 'Murudesh.Ceramic'},
  {id:'NITCO', val: 'Nitco'},
  {id:'ORIENTBELL', val: 'Orient Bell'},
  {id:'REGENCERAM', val: 'Regency Ceramics'},
  {id:'SOMANYCERA', val: 'Somany Ceramics'},
  {id:'ASTRAMICRO', val: 'Astra Microwave'},
  {id:'GTL', val: 'GTL'},
  {id:'GTLINFRA', val: 'GTL Infra.'},
  {id:'INDUSTOWER', val: 'Indus Towers'},
  {id:'ITI', val: 'ITI'},
  {id:'KAVVERITEL', val: 'Kavveri Telecom'},
  {id:'NELCO', val: 'NELCO'},
  {id:'OLECTRA', val: 'Olectra Greentec'},
  {id:'SHYAMTEL', val: 'Shyam Telecom'},
  {id:'GLOBALVECT', val: 'Global Vectra'},
  {id:'INDIGO', val: 'Interglobe Aviat'},
  {id:'JETAIRWAYS', val: 'Jet Airways'},
  {id:'JETFREIGHT', val: 'Jet Freight'},
  {id:'SPICEJET', val: 'SpiceJet'},
  {id:'ASALCBR', val: 'Assoc.Alcohols'},
  {id:'AURDIS', val: 'Aurangabad Dist.'},
  {id:'GMBREW', val: 'G M Breweries'},
  {id:'GLOBUSSPR', val: 'Globus Spirits'},
  {id:'IFBAGRO', val: 'IFB Agro Inds.'},
  {id:'PIONDIST', val: 'Pioneer Distil.'},
  {id:'RADICO', val: 'Radico Khaitan'},
  {id:'RKDL', val: 'Ravikumar Distll'},
  {id:'SDBL', val: 'Som Distilleries'},
  {id:'TI', val: 'Tilaknagar Inds.'},
  {id:'UBL', val: 'United Breweries'},
  {id:'MCDOWELL-N', val: 'United Spirits'},
  {id:'BHARTIARTL', val: 'Bharti Airtel'},
  {id:'MTNL', val: 'M T N L'},
  {id:'ONMOBILE', val: 'OnMobile Global'},
  {id:'RAILTEL', val: 'Railtel Corpn.'},
  {id:'RCOM', val: 'Reliance Communi'},
  {id:'TATACOMM', val: 'Tata Comm'},
  {id:'TTML', val: 'Tata Tele. Mah.'},
  {id:'TEJASNET', val: 'Tejas Networks'},
  {id:'UNIINFO', val: 'Uniinfo Telecom'},
  {id:'IDEA', val: 'Vodafone Idea'},
  {id:'APOLLOHOSP', val: 'Apollo Hospitals'},
  {id:'ARTEMISMED', val: 'Artemis Medicare'},
  {id:'ASTERDM', val: 'Aster DM Health.'},
  {id:'LALPATHLAB', val: 'Dr Lal Pathlabs'},
  {id:'FORTIS', val: 'Fortis Health.'},
  {id:'HCG', val: 'Health.Global'},
  {id:'INDRAMEDCO', val: 'Indrapr.Medical'},
  {id:'KOVAI', val: 'Kovai Medical'},
  {id:'KIMS', val: 'Krishna Institu.'},
  {id:'KRSNAA', val: 'Krsnaa Diagnost.'},
  {id:'LOTUSEYE', val: 'Lotus Eye Hospit'},
  {id:'MAXHEALTH', val: 'Max Healthcare'},
  {id:'METROPOLIS', val: 'Metropolis Healt'},
  {id:'NH', val: 'Narayana Hrudaya'},
  {id:'OPTOCIRCUI', val: 'Opto Circuits'},
  {id:'POLYMED', val: 'Poly Medicure'},
  {id:'SHALBY', val: 'Shalby'},
  {id:'THYROCARE', val: 'Thyrocare Tech.'},
  {id:'AHLUCONT', val: 'Ahluwalia Contr.'},
  {id:'AJMERA', val: 'Ajmera Realty'},
  {id:'AMJLAND', val: 'AMJ Land Holdin.'},
  {id:'ANANTRAJ', val: 'Anant Raj'},
  {id:'ANSALHSG', val: 'Ansal Housing'},
  {id:'ANSALAPI', val: 'Ansal Properties'},
  {id:'ARIHANT', val: 'Arih.Found.Hsg.'},
  {id:'ARIHANTSUP', val: 'Arihant Super.'},
  {id:'ARVSMART', val: 'Arvind SmartSp.'},
  {id:'ASHIANA', val: 'Ashiana Housing'},
  {id:'BHAGYAPROP', val: 'Bhagya. Prop.'},
  {id:'BRIGADE', val: 'Brigade Enterpr.'},
  {id:'CAPACITE', val: 'Capacit\'e Infra.'},
  {id:'COUNCODOS', val: 'Country Condo'},
  {id:'DBREALTY', val: 'D B Realty'},
  {id:'DLF', val: 'DLF'},
  {id:'EMAMIREAL', val: 'Emami Realty Ltd'},
  {id:'GRINFRA', val: 'G R Infraproject'},
  {id:'GEECEE', val: 'GeeCee Vent.'},
  {id:'GODREJPROP', val: 'Godrej Propert.'},
  {id:'HDIL', val: 'H D I L'},
  {id:'HEMIPROP', val: 'Hemisphere Prop'},
  {id:'HUBTOWN', val: 'Hubtown'},
  {id:'IBREALEST', val: 'Indbull.RealEst.'},
  {id:'KARDA', val: 'Karda Construct.'},
  {id:'KAUSHALYA', val: 'Kaushalya Infra.'},
  {id:'KOLTEPATIL', val: 'Kolte Patil Dev.'},
  {id:'LPDC', val: 'Landmark Prop.'},
  {id:'MARATHON', val: 'Marathon Nextgen'},
  {id:'NBCC', val: 'NBCC'},
  {id:'NITESHEST', val: 'NEL Holdings'},
  {id:'OBEROIRLTY', val: 'Oberoi Realty'},
  {id:'OMAXE', val: 'Omaxe'},
  {id:'OSWALAGRO', val: 'Oswal Agro Mills'},
  {id:'PENINLAND', val: 'Peninsula Land'},
  {id:'PHOENIXLTD', val: 'Phoenix Mills'},
  {id:'PODDARHOUS', val: 'Poddar Housing'},
  {id:'PRAENG', val: 'Prajay Engineers'},
  {id:'PRESTIGE', val: 'Prestige Estates'},
  {id:'PROZONINTU', val: 'Prozone Intu'},
  {id:'PURVA', val: 'Puravankara'},
  {id:'PVP', val: 'PVP Ventures'},
  {id:'RVHL', val: 'Ravinder Heights'},
  {id:'SECL', val: 'Salasar Exterior'},
  {id:'SHRADHA', val: 'Shradha Infrapr.'},
  {id:'SOBHA', val: 'Sobha'},
  {id:'SPMLINFRA', val: 'SPML Infra'},
  {id:'SUMIT', val: 'Sumit Woods'},
  {id:'SUNTECK', val: 'Sunteck Realty'},
  {id:'TARC', val: 'TARC Ltd'},
  {id:'TARMAT', val: 'Tarmat'},
  {id:'TCIDEVELOP', val: 'TCI Developers'},
  {id:'TECHIN', val: 'Techindia Nirman'},
  {id:'TEXINFRA', val: 'Texmaco Infrast.'},
  {id:'UNITECH', val: 'Unitech'},
  {id:'VIPULLTD', val: 'Vipul Ltd'},
  {id:'ZUARIGLOB', val: 'Zuari Global'},
  {id:'AVADHSUGAR', val: 'Avadh Sugar'},
  {id:'BAJAJHIND', val: 'Bajaj Hindusthan'},
  {id:'BALRAMCHIN', val: 'Balrampur Chini'},
  {id:'BANARISUG', val: 'Bannari Amm.Sug.'},
  {id:'DALMIASUG', val: 'Dalmia Bharat'},
  {id:'DHAMPURSUG', val: 'Dhampur Sugar'},
  {id:'DHARSUGAR', val: 'Dharani Sugars'},
  {id:'DWARKESH', val: 'Dwarikesh Sugar'},
  {id:'EIDPARRY', val: 'EID Parry'},
  {id:'KCPSUGIND', val: 'KCP Sugar &Inds.'},
  {id:'KESARENT', val: 'Kesar Enterprise'},
  {id:'KMSUGAR', val: 'KM Sugar Mills'},
  {id:'KOTARISUG', val: 'Kothari Sugars'},
  {id:'MAGADSUGAR', val: 'Magadh Sugar'},
  {id:'MAWANASUG', val: 'Mawana Sugars'},
  {id:'PONNIERODE', val: 'Ponni Sug.Erode'},
  {id:'RAJSREESUG', val: 'Rajshree Sugars'},
  {id:'RANASUG', val: 'Rana Sugars'},
  {id:'SAKHTISUG', val: 'Sakthi Sugars'},
  {id:'RENUKA', val: 'Sh.Renuka Sugar'},
  {id:'SIMBHALS', val: 'Simbhaoli Sugar'},
  {id:'TRIVENI', val: 'Triven.Engg.Ind.'},
  {id:'UGARSUGAR', val: 'Ugar Sugar Works'},
  {id:'UTTAMSUGAR', val: 'Uttam Sug.Mills'},
  {id:'VISHWARAJ', val: 'Vishwaraj Sugar'},
  {id:'ACRYSIL', val: 'Acrysil'},
  {id:'AMBER', val: 'Amber Enterp.'},
  {id:'BAJAJELEC', val: 'Bajaj Electrical'},
  {id:'BLUESTARCO', val: 'Blue Star'},
  {id:'BPL', val: 'BPL'},
  {id:'BUTTERFLY', val: 'Butterfly Gan Ap'},
  {id:'DELTAMAGNT', val: 'Delta Manufact.'},
  {id:'DIXON', val: 'Dixon Technolog.'},
  {id:'EUROMULTI', val: 'Euro Multivision'},
  {id:'GENUSPOWER', val: 'Genus Power'},
  {id:'HIRECT', val: 'Hind Rectifiers'},
  {id:'HONAUT', val: 'Honeywell Auto'},
  {id:'IFBIND', val: 'IFB Industries'},
  {id:'JCHAC', val: 'Johnson Con. Hit'},
  {id:'KDDL', val: 'KDDL Ltd'},
  {id:'MIRCELECTR', val: 'MIRC Electronics'},
  {id:'ORIENTELEC', val: 'Orient Electric'},
  {id:'PGEL', val: 'PG Electroplast'},
  {id:'SALORAINTL', val: 'Salora Intl.'},
  {id:'SONAMCLOCK', val: 'Sonam Clock'},
  {id:'STOVEKRAFT', val: 'Stove Kraft'},
  {id:'SYMPHONY', val: 'Symphony'},
  {id:'TTKPRESTIG', val: 'TTK Prestige'},
  {id:'VOLTAS', val: 'Voltas'},
  {id:'WHIRLPOOL', val: 'Whirlpool India'},
  {id:'DSML', val: 'Debock Sales'},
  {id:'EMKAYTOOLS', val: 'Emkay Taps & Cut'},
  {id:'HMT', val: 'HMT'},
  {id:'ICEMAKE', val: 'ICE Make Refrig.'},
  {id:'MACPOWER', val: 'Macpower CNC'},
  {id:'MARSHALL', val: 'Marshall Machin.'},
  {id:'MBECL', val: 'McNally Bharat'},
  {id:'MOLDTECH', val: 'Mold-Tek Technol'},
  {id:'MTARTECH', val: 'MTAR Technologie'},
  {id:'OMINFRAL', val: 'Om Infra'},
  {id:'PERFECT', val: 'Perfect Infraeng'},
  {id:'SKIPPER', val: 'Skipper'},
  {id:'SWSOLAR', val: 'Sterling & Wils.'},
  {id:'ANUP', val: 'The Anup Enginee'},
  {id:'THEJO', val: 'Thejo Engg.'},
  {id:'TRANSWIND', val: 'Transwind Infra.'},
  {id:'GICRE', val: 'General Insuranc'},
  {id:'HDFCLIFE', val: 'HDFC Life Insur.'},
  {id:'ICICIGI', val: 'ICICI Lombard'},
  {id:'ICICIPRULI', val: 'ICICI Pru Life'},
  {id:'NIACL', val: 'New India Assura'},
  {id:'SBILIFE', val: 'SBI Life Insuran'},
  {id:'AHLADA', val: 'Ahlada Engineers'},
  {id:'ANKITMETAL', val: 'Ankit Met.Power'},
  {id:'APLAPOLLO', val: 'APL Apollo Tubes'},
  {id:'BEDMUTHA', val: 'Bedmutha Indus.'},
  {id:'BHARATWIRE', val: 'Bharat Wire'},
  {id:'DPWIRES', val: 'D P Wires'},
  {id:'ELECTHERM', val: 'Electrotherm(I)'},
  {id:'GALLISPAT', val: 'Gallantt Ispat'},
  {id:'GALLANTT', val: 'Gallantt Metal'},
  {id:'GANDHITUBE', val: 'Gandhi Spl. Tube'},
  {id:'GPIL', val: 'Godawari Power'},
  {id:'GOODLUCK', val: 'Goodluck India'},
  {id:'GFSTEELS', val: 'Grand Foundry'},
  {id:'GAL', val: 'Gyscoal Alloys'},
  {id:'HITECH', val: 'Hi-Tech Pipes'},
  {id:'HISARMETAL', val: 'Hisar Met.Inds.'},
  {id:'INCREDIBLE', val: 'Incredible Indus'},
  {id:'ISMTLTD', val: 'ISMT'},
  {id:'JAIBALAJI', val: 'Jai Balaji Inds.'},
  {id:'JINDALSAW', val: 'Jindal Saw'},
  {id:'JSL', val: 'Jindal Stain.'},
  {id:'JSLHISAR', val: 'Jindal Stain. Hi'},
  {id:'JINDALSTEL', val: 'Jindal Steel'},
  {id:'JSWISPL', val: 'JSW Ispat Speci.'},
  {id:'JSWSTEEL', val: 'JSW Steel'},
  {id:'KSL', val: 'Kalyani Steels'},
  {id:'KAMDHENU', val: 'Kamdhenu'},
  {id:'KIRLFER', val: 'Kirl. Ferrous'},
  {id:'KRITIKA', val: 'Kritika Wires'},
  {id:'LSIL', val: 'Lloyds Steels'},
  {id:'MAHSEAMLES', val: 'Mah. Seamless'},
  {id:'MAHASTEEL', val: 'Mahamaya Steel'},
  {id:'MANINDS', val: 'Man Industries'},
  {id:'MANAKCOAT', val: 'Manaksia Coated'},
  {id:'MANAKSTEEL', val: 'Manaksia Steels'},
  {id:'MIDHANI', val: 'Mishra Dhatu Nig'},
  {id:'MSPL', val: 'MSP Steel & Pow.'},
  {id:'MUKANDLTD', val: 'Mukand'},
  {id:'NATNLSTEEL', val: 'Natl. Steel&Agro'},
  {id:'OILCOUNTUB', val: 'Oil Country'},
  {id:'PENIND', val: 'Pennar Industrie'},
  {id:'PRAKASH', val: 'Prakash Industri'},
  {id:'PRAKASHSTL', val: 'Prakash Steelage'},
  {id:'RAJRATAN', val: 'Rajratan Global'},
  {id:'RAMASTEEL', val: 'Rama Steel Tubes'},
  {id:'RATNAMANI', val: 'Ratnamani Metals'},
  {id:'SAIL', val: 'S A I L'},
  {id:'SALSTEEL', val: 'S.A.L Steel'},
  {id:'SALASAR', val: 'Salasar Techno'},
  {id:'SARDAEN', val: 'Sarda Energy'},
  {id:'SATHAISPAT', val: 'Sathavaha. Ispat'},
  {id:'SHAHALLOYS', val: 'Shah Alloys'},
  {id:'SHYAMMETL', val: 'Shyam Metalics'},
  {id:'SRIPIPES', val: 'Srikalahas. Pip.'},
  {id:'SUNFLAG', val: 'Sunflag Iron'},
  {id:'SUPREMEENG', val: 'Supreme Engg.'},
  {id:'SURANI', val: 'Surani Steel Tub'},
  {id:'SURYAROSNI', val: 'Surya Roshni'},
  {id:'TATAMETALI', val: 'Tata Metaliks'},
  {id:'TATASTEEL', val: 'Tata Steel'},
  {id:'TATASTLBSL', val: 'Tata Steel BSL'},
  {id:'TATASTLLP', val: 'Tata Steel Long'},
  {id:'TIIL', val: 'Technocraf.Inds.'},
  {id:'USHAMART', val: 'Usha Martin'},
  {id:'UTTAMSTL', val: 'Uttam Galva Stee'},
  {id:'VSSL', val: 'Vardhman Special'},
  {id:'VASWANI', val: 'Vaswani Industri'},
  {id:'VISASTEEL', val: 'Visa Steel'},
  {id:'WELCORP', val: 'Welspun Corp'},
  {id:'ZENITHSTL', val: 'Zenith Steel'},
  {id:'CYBERMEDIA', val: 'Cyber Media Ind'},
  {id:'ABFRL', val: 'Aditya Bir. Fas.'},
  {id:'ARCHIES', val: 'Archies'},
  {id:'ARVINDFASN', val: 'Arvind Fashions.'},
  {id:'DMART', val: 'Avenue Super.'},
  {id:'FELDVR', val: 'Future Ent. DVR'},
  {id:'FEL', val: 'Future Enterp.'},
  {id:'FLFL', val: 'Future Lifestyle'},
  {id:'FRETAIL', val: 'Future Retail'},
  {id:'TMRVL', val: 'Mandhana Retail'},
  {id:'OSIAHYPER', val: 'Osia Hyper Reta.'},
  {id:'SHOPERSTOP', val: 'Shoppers Stop'},
  {id:'SPENCERS', val: 'Spencer\'s Retail'},
  {id:'TRENT', val: 'Trent'},
  {id:'VMART', val: 'V-Mart Retail'},
  {id:'V2RETAIL', val: 'V2 Retail'},
  {id:'ALICON', val: 'Alicon Cast.'},
  {id:'AMARAJABAT', val: 'Amara Raja Batt.'},
  {id:'ASLIND', val: 'ASL Industries'},
  {id:'AUTOIND', val: 'Autoline Industr'},
  {id:'AUTOLITIND', val: 'Autolite (I)'},
  {id:'AUTOAXLES', val: 'Automotive Axles'},
  {id:'ASAL', val: 'Automotive Stamp'},
  {id:'BANCOINDIA', val: 'Banco Products'},
  {id:'BHARATGEAR', val: 'Bharat Gears'},
  {id:'BOSCHLTD', val: 'Bosch'},
  {id:'CRAFTSMAN', val: 'Craftsman Auto'},
  {id:'ENDURANCE', val: 'Endurance Tech.'},
  {id:'EXIDEIND', val: 'Exide Inds.'},
  {id:'FMGOETZE', val: 'Federal-Mogul Go'},
  {id:'FIEMIND', val: 'Fiem Industries'},
  {id:'GABRIEL', val: 'Gabriel India'},
  {id:'GNA', val: 'GNA Axles'},
  {id:'HINDCOMPOS', val: 'Hind.Composites'},
  {id:'IGARASHI', val: 'Igarashi Motors'},
  {id:'IMPAL', val: 'India Motor Part'},
  {id:'INDNIPPON', val: 'India Nipp.Elec.'},
  {id:'JAMNAAUTO', val: 'Jamna Auto Inds.'},
  {id:'JAYBARMARU', val: 'Jay Bharat Maru.'},
  {id:'JBMA', val: 'JBM Auto'},
  {id:'JMTAUTOLTD', val: 'JMT Auto'},
  {id:'JTEKTINDIA', val: 'JTEKT India'},
  {id:'JMA', val: 'Jullundur Motor'},
  {id:'LGBBROSLTD', val: 'L G Balakrishnan'},
  {id:'LUMAXTECH', val: 'Lumax Auto Tech.'},
  {id:'LUMAXIND', val: 'Lumax Industries'},
  {id:'MENONBE', val: 'Menon Bearings'},
  {id:'MINDACORP', val: 'Minda Corp'},
  {id:'MINDAIND', val: 'Minda Industries'},
  {id:'MOTHERSUMI', val: 'Motherson Sumi'},
  {id:'MUNJALAU', val: 'Munjal Auto Inds'},
  {id:'MUNJALSHOW', val: 'Munjal Showa'},
  {id:'NDRAUTO', val: 'NDR Auto Compon.'},
  {id:'NRBBEARING', val: 'NRB Bearings'},
  {id:'OMAXAUTO', val: 'Omax Autos'},
  {id:'PAEL', val: 'PAE'},
  {id:'PPAP', val: 'PPAP Automotive'},
  {id:'PRECAM', val: 'Precision Camshf'},
  {id:'PRICOLLTD', val: 'Pricol Ltd'},
  {id:'PRITIKAUTO', val: 'Pritika Auto'},
  {id:'RML', val: 'Rane (Madras)'},
  {id:'RBL', val: 'Rane Brake Lin.'},
  {id:'RANEENGINE', val: 'Rane Engine Val.'},
  {id:'REMSONSIND', val: 'Remsons Ind'},
  {id:'RICOAUTO', val: 'Rico Auto Inds'},
  {id:'ROLEXRINGS', val: 'Rolex Rings'},
  {id:'SANDHAR', val: 'Sandhar Tech'},
  {id:'SETCO', val: 'Setco Automotive'},
  {id:'SHANTIGEAR', val: 'Shanthi Gears'},
  {id:'SHARDAMOTR', val: 'Sharda Motor'},
  {id:'SHIVAMAUTO', val: 'Shivam Autotech'},
  {id:'SHRIPISTON', val: 'Shriram Pistons'},
  {id:'SINTERCOM', val: 'Sintercom India'},
  {id:'SSWL', val: 'Steel Str. Wheel'},
  {id:'SUBROS', val: 'Subros'},
  {id:'SUNDRMBRAK', val: 'Sundaram Brake'},
  {id:'SUNCLAYLTD', val: 'Sundaram Clayton'},
  {id:'SUPRAJIT', val: 'Suprajit Engg.'},
  {id:'TALBROAUTO', val: 'Talbros Auto.'},
  {id:'HITECHGEAR', val: 'The Hi-Tech Gear'},
  {id:'TIMKEN', val: 'Timken India'},
  {id:'UCALFUEL', val: 'Ucal Fuel Sys.'},
  {id:'UWCSL', val: 'Ultra Wiring'},
  {id:'VARROC', val: 'Varroc Engineer'},
  {id:'WABCOINDIA', val: 'WABCO India'},
  {id:'WHEELS', val: 'Wheels India'},
  {id:'ADVANIHOTR', val: 'Advani Hotels.'},
  {id:'APOLSINHOT', val: 'Apollo Sindoori'},
  {id:'AHLEAST', val: 'Asian Hotels (E)'},
  {id:'ASIANHOTNR', val: 'Asian Hotels (N)'},
  {id:'AHLWEST', val: 'Asian Hotels (W)'},
  {id:'BARBEQUE', val: 'Barbeque-Nation'},
  {id:'BLUECOAST', val: 'Blu.Coast Hotel.'},
  {id:'CHALET', val: 'Chalet Hotels'},
  {id:'CCHHL', val: 'Country Club Hos'},
  {id:'EIHOTEL', val: 'EIH'},
  {id:'EIHAHOTELS', val: 'EIH Assoc.Hotels'},
  {id:'HLVLTD', val: 'HLV'},
  {id:'HOTELRUGBY', val: 'Hotel Rugby'},
  {id:'ITDC', val: 'I T D C'},
  {id:'INDHOTEL', val: 'Indian Hotels Co'},
  {id:'KAMATHOTEL', val: 'Kamat Hotels'},
  {id:'KHFM', val: 'KHFM Hospitality'},
  {id:'LEMONTREE', val: 'Lemon Tree Hotel'},
  {id:'MHRIL', val: 'Mahindra Holiday'},
  {id:'ORIENTHOT', val: 'Oriental Hotels'},
  {id:'ROHLTD', val: 'Royal Orch.Hotel'},
  {id:'SPECIALITY', val: 'Speciality Rest.'},
  {id:'TAJGVK', val: 'TajGVK Hotels'},
  {id:'TGBHOTELS', val: 'TGB Banquets'},
  {id:'BYKE', val: 'The Byke Hospi.'},
  {id:'VICEROY', val: 'Viceroy Hotels'},
  {id:'BEL', val: 'Bharat Electron'},
  {id:'CENTUM', val: 'Centum Electron'},
  {id:'KERNEX', val: 'Kernex Microsys.'},
  {id:'NITIRAJ', val: 'Nitiraj Engineer'},
  {id:'PULZ', val: 'Pulz Electronics'},
  {id:'SBCL', val: 'Shivalik Bimetal'},
  {id:'IRCTC', val: 'I R C T C'},
  {id:'ACCORD', val: 'Accord Synergy'},
  {id:'ADANIPORTS', val: 'Adani Ports'},
  {id:'AJRINFRA', val: 'AJR Infra &'},
  {id:'AISL', val: 'ANI Integrated'},
  {id:'ASHOKA', val: 'Ashoka Buildcon'},
  {id:'ATALREAL', val: 'Atal Realtech'},
  {id:'ATLANTA', val: 'Atlanta'},
  {id:'BGRENERGY', val: 'BGR Energy Sys.'},
  {id:'DBL', val: 'Dilip Buildcon'},
  {id:'ENGINERSIN', val: 'Engineers India'},
  {id:'GEPIL', val: 'GE Power'},
  {id:'GMRINFRA', val: 'GMR Infra.'},
  {id:'HECPROJECT', val: 'HEC Infra Proj.'},
  {id:'HFCL', val: 'HFCL'},
  {id:'IL&FSENGG', val: 'IL&FS Engg.'},
  {id:'IL&FSTRANS', val: 'IL&FS Transport'},
  {id:'IRB', val: 'IRB Infra.Devl.'},
  {id:'IRCON', val: 'Ircon Intl.'},
  {id:'JKIL', val: 'J Kumar Infra'},
  {id:'JPINFRATEC', val: 'Jaypee Infratech'},
  {id:'LT', val: 'Larsen & Toubro'},
  {id:'LIKHITHA', val: 'Likhitha Infra.'},
  {id:'MEP', val: 'MEP Infrast.'},
  {id:'MUKANDENGG', val: 'Mukand Engineers'},
  {id:'NOIDATOLL', val: 'Noida Tollbridg.'},
  {id:'PIGL', val: 'Power & Instrum.'},
  {id:'RIIL', val: 'Rel. Indl. Infra'},
  {id:'RELINFRA', val: 'Reliance Infra.'},
  {id:'RITES', val: 'Rites'},
  {id:'SHRIRAMEPC', val: 'Shriram EPC'},
  {id:'TANTIACONS', val: 'Tantia Constr.'},
  {id:'TECHNOE', val: 'Techno Elec.Engg'},
  {id:'WSI', val: 'W S Inds.'},
  {id:'ZODIAC', val: 'Zodiac Energy'},
  {id:'ATFL', val: 'Agro Tech Foods.'},
  {id:'AVTNPL', val: 'AVT Natural Prod'},
  {id:'BCLIND', val: 'BCL Industries'},
  {id:'GOKULAGRO', val: 'Gokul Agro'},
  {id:'GOKUL', val: 'Gokul Refoils'},
  {id:'GAEL', val: 'Guj. Ambuja Exp'},
  {id:'MGEL', val: 'Mangalam Global'},
  {id:'NKIND', val: 'N K Industries'},
  {id:'ROML', val: 'Raj Oil Mills'},
  {id:'RUCHI', val: 'Ruchi Soya Inds.'},
  {id:'SRPL', val: 'Shree Ram Proti.'}
   
]


export {arrStocks};